"""
Investigation service — Wave 5/6/7 convergence (thin facade).
"""
from services.investigation_crud import (
    create_investigation,
    delete_investigation,
    generate_action_number,
    generate_case_number,
    update_investigation,
)
from services.investigation_files import (
    ai_problem_check,
    download_file,
    upload_investigation_file,
)
from services.investigation_queries import (
    check_for_similar_incidents,
    get_investigation_detail,
    get_linked_incident,
    get_similar_incidents,
    inv_child_query,
    investigation_query,
    list_investigations,
)
from services.investigation_subresources import (
    add_evidence,
    create_action_item,
    create_cause_node,
    create_failure_identification,
    create_timeline_event,
    delete_action_item,
    delete_cause_node,
    delete_evidence,
    delete_failure_identification,
    delete_timeline_event,
    link_incident,
    unlink_incident,
    update_action_item,
    update_cause_node,
    update_failure_identification,
    update_recurring_quadrant,
    update_timeline_event,
)

__all__ = [
    "investigation_query",
    "inv_child_query",
    "list_investigations",
    "get_investigation_detail",
    "check_for_similar_incidents",
    "generate_case_number",
    "generate_action_number",
    "create_investigation",
    "update_investigation",
    "delete_investigation",
    "create_timeline_event",
    "update_timeline_event",
    "delete_timeline_event",
    "create_failure_identification",
    "update_failure_identification",
    "delete_failure_identification",
    "create_cause_node",
    "update_cause_node",
    "delete_cause_node",
    "create_action_item",
    "update_action_item",
    "delete_action_item",
    "add_evidence",
    "delete_evidence",
    "get_similar_incidents",
    "get_linked_incident",
    "update_recurring_quadrant",
    "link_incident",
    "unlink_incident",
    "upload_investigation_file",
    "download_file",
    "ai_problem_check",
]
