/** Onboarding phase content — copy, demo type, and CTA targets. */
export const ONBOARDING_PHASES = [
  {
    id: "company",
    label: "Company",
    what: "This is your company profile.",
    why: "These settings are used throughout the entire platform.",
    demo: "company",
    ctaLabel: "Configure Company Settings",
    ctaPath: "/settings/general",
    help: {
      explainAgain: "Your company profile sets the name, language, and timezone AssetIQ uses everywhere.",
      bestPractice: "Use your legal company name and the timezone where most maintenance work is planned.",
      example: "company",
    },
  },
  {
    id: "sites",
    label: "Sites",
    what: "Sites represent the locations where your assets operate.",
    why: "Everything inside AssetIQ belongs to a site.",
    demo: "sites",
    ctaLabel: "Create Your First Site",
    ctaPath: "/equipment-manager",
    help: {
      explainAgain: "A site is the top level of your ISO 14224 hierarchy — plants and equipment live underneath it.",
      bestPractice: "Create one site per physical location or operating unit.",
      example: "sites",
    },
  },
  {
    id: "equipment",
    label: "Equipment",
    what: "This is the structure of the assets you maintain.",
    why: "All observations, inspections and maintenance are linked to equipment.",
    demo: "equipment",
    ctaLabel: "Import Equipment",
    ctaPath: "/equipment-manager",
    help: {
      explainAgain: "Equipment is organized in a hierarchy from plant down to maintainable items.",
      bestPractice: "Import from Excel or use AI Process Import for P&IDs before adding failure modes.",
      example: "equipment",
    },
  },
  {
    id: "users",
    label: "Users",
    what: "Users receive access based on their role.",
    why: "Everyone only sees the equipment they are responsible for.",
    demo: "users",
    ctaLabel: "Invite Users",
    ctaPath: "/settings/user-management",
    help: {
      explainAgain: "Assign roles and installations so each person sees the right equipment.",
      bestPractice: "Invite at least one reliability engineer and assign installations to every user.",
      example: "users",
    },
  },
  {
    id: "criticality",
    label: "Criticality",
    what: "Criticality tells AssetIQ which equipment matters most.",
    why: "AssetIQ uses this to prioritize work.",
    demo: "criticality",
    ctaLabel: "Review Criticality Settings",
    ctaPath: "/settings/risk-calculation",
    help: {
      explainAgain: "Safety, production, environmental and reputation scores drive risk ranking.",
      bestPractice: "Review criticality definitions per installation before go-live.",
      example: "criticality",
    },
  },
  {
    id: "failure_modes",
    label: "Failure Modes",
    what: "Failure Modes describe how equipment can fail.",
    why: "They drive maintenance strategy and AI recommendations.",
    demo: "failure_modes",
    ctaLabel: "Import PM Plan",
    ctaPath: "/library",
    help: {
      explainAgain: "Customer-specific failure modes capture your plant's reliability knowledge.",
      bestPractice: "Use PM Import from the Strategy library — it links tasks to equipment automatically.",
      example: "failure_modes",
    },
  },
  {
    id: "maintenance_strategy",
    label: "Maintenance Strategy",
    what: "Maintenance Strategies tell AssetIQ what work should happen.",
    why: "They automatically generate maintenance tasks.",
    demo: "maintenance_strategy",
    ctaLabel: "Apply Maintenance Strategy",
    ctaPath: "/library",
    help: {
      explainAgain: "Strategies turn failure modes into scheduled inspections and PM tasks.",
      bestPractice: "Apply strategy per equipment type from the Maintenance Schedule tab.",
      example: "maintenance_strategy",
    },
  },
  {
    id: "spare_parts",
    label: "Spare Parts",
    what: "Spare parts ensure technicians know what is required.",
    why: "Linked spares reduce repair time.",
    demo: "spare_parts",
    ctaLabel: "Import Spare Parts",
    ctaPath: "/spareiq",
    help: {
      explainAgain: "SpareIQ links parts to equipment tags so work orders show what to bring.",
      bestPractice: "Import spares after equipment hierarchy is in place.",
      example: "spare_parts",
    },
  },
  {
    id: "forms",
    label: "Digital Forms",
    what: "Forms standardize inspections.",
    why: "Consistent inspections produce better reliability information.",
    demo: "forms",
    ctaLabel: "Create Your First Inspection",
    ctaPath: "/tasks?tab=forms",
    help: {
      explainAgain: "Digital forms capture structured inspection data on the shop floor.",
      bestPractice: "Start with one inspection form for your highest-criticality equipment.",
      example: "forms",
    },
  },
  {
    id: "visual_boards",
    label: "Visual Management",
    what: "Visual Boards keep everyone aligned.",
    why: "Everyone sees the same priorities.",
    demo: "visual_boards",
    ctaLabel: "Publish Your First Board",
    ctaPath: "/settings/visual-management/boards",
    help: {
      explainAgain: "TV dashboards show tasks, observations, and risk for the shop floor.",
      bestPractice: "Clone a template, publish a board, then pair a display for kiosk mode.",
      example: "visual_boards",
    },
  },
  {
    id: "external_api",
    label: "External API",
    what: "The External API allows other systems to exchange information with AssetIQ.",
    why: "It prevents duplicate data entry.",
    demo: "external_api",
    ctaLabel: "Generate API Key",
    ctaPath: "/settings/external-api",
    help: {
      explainAgain: "API keys let PLCs, CMMS, or custom apps send observations to AssetIQ.",
      bestPractice: "Create a dedicated key per integration and share the integration guide with vendors.",
      example: "external_api",
    },
  },
  {
    id: "go_live",
    label: "Go Live",
    what: "This confirms your AssetIQ environment is ready.",
    why: "It ensures everything has been configured correctly.",
    demo: "go_live",
    ctaLabel: "Run Go-Live Validation",
    ctaPath: null,
    help: {
      explainAgain: "Go-live validation checks every onboarding phase and surfaces remaining actions.",
      bestPractice: "Resolve all action-required items before handing the tenant to production users.",
      example: "go_live",
    },
  },
];

export const ENTRY_PATH_CARDS = [
  { id: "equipment_list", icon: "equipment" },
  { id: "pm_procedures", icon: "pm" },
  { id: "pid_drawings", icon: "pid" },
  { id: "spare_parts", icon: "spares" },
  { id: "integrations", icon: "api" },
  { id: "from_scratch", icon: "scratch" },
];

export function getPhaseConfig(phaseId) {
  return ONBOARDING_PHASES.find((p) => p.id === phaseId);
}
