import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

// English translations
const en = {
  // Navigation
  nav: {
    threats: "Threats",
    causalEngine: "Causal Engine",
    actions: "Actions",
    library: "Library",
    equipmentManager: "Equipment Manager",
    settings: "Settings",
    logout: "Logout",
  },
  
  // Common
  common: {
    search: "Search",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    update: "Update",
    create: "Create",
    close: "Close",
    loading: "Loading...",
    noResults: "No results found",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    all: "All",
    open: "Open",
    closed: "Closed",
    inProgress: "In Progress",
    status: "Status",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    critical: "Critical",
    name: "Name",
    description: "Description",
    date: "Date",
    time: "Time",
    comment: "Comment",
    comments: "Comments",
    evidence: "Evidence",
    owner: "Owner",
    dueDate: "Due Date",
    category: "Category",
    type: "Type",
    asset: "Asset",
    location: "Location",
  },
  
  // Threats page
  threats: {
    title: "Threats",
    totalThreats: "Total Threats",
    openThreats: "Open Threats",
    highPriority: "High Priority",
    searchPlaceholder: "Search threats...",
    reportThreat: "Report Threat",
    noThreats: "No threats reported",
    noThreatsDesc: "Click the + button to report your first threat",
    riskScore: "Risk Score",
    riskLevel: "Risk Level",
    rank: "Rank",
    failureMode: "Failure Mode",
    equipmentType: "Equipment Type",
    impact: "Impact",
    frequency: "Frequency",
    likelihood: "Likelihood",
    detectability: "Detectability",
    recommendedActions: "Recommended Actions",
    viewDetails: "View full details",
    startInvestigation: "Start Investigation",
    editThreat: "Edit Threat",
    deleteThreat: "Delete Threat",
  },
  
  // Causal Engine
  causal: {
    title: "Causal Engine",
    investigations: "Investigations",
    newInvestigation: "New Investigation",
    overview: "Overview",
    timeline: "Timeline",
    failures: "Failures",
    causalTree: "Causal Tree",
    causes: "Causes",
    rootCauses: "Root Causes",
    events: "Events",
    sequenceOfEvents: "Sequence of Events",
    reconstructTimeline: "Reconstruct the timeline",
    addEvent: "Add Event",
    noEvents: "No events recorded",
    startAddingEvents: "Start by adding the first event",
    failureIdentification: "Failure Identification",
    defineFailure: "Define what technically failed",
    addFailure: "Add Failure",
    noFailures: "No failures identified",
    documentFailure: "Document what failed",
    buildCausalTree: "Build cause-and-effect relationships",
    addCause: "Add Cause",
    noCauses: "No causes identified",
    startBuildingTree: "Start building the causal tree",
    correctiveActions: "Corrective Actions",
    trackActions: "Track actions to prevent recurrence",
    addAction: "Add Action",
    noActions: "No actions defined",
    defineActions: "Define corrective actions",
    markAsRootCause: "Mark as Root Cause",
    parent: "Parent",
    confidence: "Confidence",
    evidenceSource: "Evidence Source",
    mechanism: "Mechanism",
    subsystem: "Subsystem",
    component: "Component",
    linkedRootCause: "Linked Root Cause",
    act: "Act",
    lead: "Lead",
    incidentDate: "Incident Date",
    draft: "Draft",
  },
  
  // Actions page
  actionsPage: {
    title: "Actions",
    totalActions: "Total Actions",
    pendingActions: "Pending",
    completedActions: "Completed",
    overdueActions: "Overdue",
    searchPlaceholder: "Search actions...",
    addAction: "Add Action",
    noActions: "No actions yet",
    noActionsDesc: "Actions will appear here when you promote recommendations from threats or investigations",
    source: "Source",
    assignedTo: "Assigned To",
    notStarted: "Not Started",
    completed: "Completed",
    filterByStatus: "Filter by status",
    allStatus: "All Status",
  },
  
  // Library page
  library: {
    title: "Library",
    failureModes: "Failure Modes",
    equipmentTypes: "Equipment Types",
    totalModes: "Total Modes",
    categories: "Categories",
    searchPlaceholder: "Search failure modes...",
    addFailureMode: "Add Failure Mode",
    addEquipmentType: "Add Type",
    noFailureModes: "No failure modes found",
    linkedEquipmentTypes: "Linked Equipment Types",
    selectEquipmentTypes: "Select equipment types...",
    discipline: "Discipline",
    mechanical: "Mechanical",
    electrical: "Electrical",
    instrumentation: "Instrumentation",
    process: "Process",
    icon: "Icon",
    isoClass: "ISO Class",
    typeId: "Type ID (unique)",
  },
  
  // Equipment Manager
  equipment: {
    title: "Equipment Manager",
    hierarchy: "Hierarchy",
    tree: "Tree",
    levels: "Levels",
    properties: "Properties",
    addInstallation: "Add Installation",
    addChild: "Add Child",
    importList: "Import List",
    searchPlaceholder: "Search name, description, tag...",
    matches: "matches",
    noEquipment: "No equipment in hierarchy",
    addFirstEquipment: "Add your first installation to get started",
    selectNode: "Select a node",
    selectNodeDesc: "Click on an equipment item to view and edit its properties",
    installation: "Installation",
    plant: "Plant/Unit",
    section: "Section",
    equipmentUnit: "Equipment Unit",
    subunit: "Subunit",
    maintainableItem: "Maintainable Item",
    tag: "Tag",
    criticality: "Criticality",
    selectCriticality: "Select criticality...",
    safetyCritical: "Safety Critical",
    productionCritical: "Production Critical",
    noCriticality: "No criticality assigned",
    clearCriticality: "Clear criticality",
    dragDropHint: "Drag items to reorder or change hierarchy",
    unassigned: "Unassigned Items",
  },
  
  // Chat
  chat: {
    title: "Report Threat",
    subtitle: "Describe the failure",
    placeholder: "Describe the issue...",
    welcomeMessage: "Hi! I'm here to help you report equipment threats. Just describe what's happening - mention the equipment and the problem, and I'll create a threat record for you.",
    threatRecorded: "Threat recorded successfully.",
    attachPhoto: "Attach photo",
    voiceInput: "Voice input",
  },
  
  // Info dialog
  info: {
    title: "ThreatBase - Risk Methodology",
    fmeaScoring: "FMEA Risk Scoring",
    fmeaDescription: "Risk scores are calculated using Failure Mode and Effects Analysis (FMEA) methodology:",
    formula: "Risk Score = (Severity × Occurrence × Detection) / 10",
    maxScore: "Maximum score: 100",
    severity: "Severity (Impact)",
    safetyHazard: "Safety Hazard",
    productionLoss: "Production Loss",
    equipmentDamage: "Equipment Damage",
    environmental: "Environmental",
    occurrence: "Occurrence (Frequency)",
    firstTime: "First Time",
    rare: "Rare",
    occasional: "Occasional",
    frequent: "Frequent",
    detection: "Detection (Difficulty)",
    easy: "Easy",
    moderate: "Moderate",
    difficult: "Difficult",
    riskLevels: "Risk Levels",
    criticalityMultipliers: "Equipment Criticality Multipliers",
    criticalityDescription: "Risk scores are adjusted based on equipment criticality:",
    quickTips: "Quick Tips",
    tip1: "Use the + button to report new threats via chat",
    tip2: "Drag and drop equipment in the hierarchy to reorganize",
    tip3: "Click on a threat to view details and start investigations",
    tip4: "Use the Causal Engine to perform root cause analysis",
    tip5: "Promote recommendations to Actions for tracking",
  },
  
  // Auth
  auth: {
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    name: "Name",
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your account",
    registerTitle: "Create account",
    registerSubtitle: "Start managing equipment threats",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    signUp: "Sign up",
    signIn: "Sign in",
  },
};

// Dutch translations
const nl = {
  // Navigation
  nav: {
    threats: "Dreigingen",
    causalEngine: "Oorzaakanalyse",
    actions: "Acties",
    library: "Bibliotheek",
    equipmentManager: "Apparatuurbeheer",
    settings: "Instellingen",
    logout: "Uitloggen",
  },
  
  // Common
  common: {
    search: "Zoeken",
    add: "Toevoegen",
    edit: "Bewerken",
    delete: "Verwijderen",
    cancel: "Annuleren",
    save: "Opslaan",
    update: "Bijwerken",
    create: "Aanmaken",
    close: "Sluiten",
    loading: "Laden...",
    noResults: "Geen resultaten gevonden",
    confirm: "Bevestigen",
    yes: "Ja",
    no: "Nee",
    all: "Alle",
    open: "Open",
    closed: "Gesloten",
    inProgress: "In uitvoering",
    status: "Status",
    priority: "Prioriteit",
    high: "Hoog",
    medium: "Gemiddeld",
    low: "Laag",
    critical: "Kritiek",
    name: "Naam",
    description: "Beschrijving",
    date: "Datum",
    time: "Tijd",
    comment: "Opmerking",
    comments: "Opmerkingen",
    evidence: "Bewijs",
    owner: "Eigenaar",
    dueDate: "Vervaldatum",
    category: "Categorie",
    type: "Type",
    asset: "Asset",
    location: "Locatie",
  },
  
  // Threats page
  threats: {
    title: "Dreigingen",
    totalThreats: "Totaal dreigingen",
    openThreats: "Open dreigingen",
    highPriority: "Hoge prioriteit",
    searchPlaceholder: "Zoek dreigingen...",
    reportThreat: "Dreiging melden",
    noThreats: "Geen dreigingen gemeld",
    noThreatsDesc: "Klik op de + knop om uw eerste dreiging te melden",
    riskScore: "Risicoscore",
    riskLevel: "Risiconiveau",
    rank: "Rang",
    failureMode: "Faalmodus",
    equipmentType: "Apparatuurtype",
    impact: "Impact",
    frequency: "Frequentie",
    likelihood: "Waarschijnlijkheid",
    detectability: "Detecteerbaarheid",
    recommendedActions: "Aanbevolen acties",
    viewDetails: "Bekijk details",
    startInvestigation: "Start onderzoek",
    editThreat: "Bewerk dreiging",
    deleteThreat: "Verwijder dreiging",
  },
  
  // Causal Engine
  causal: {
    title: "Oorzaakanalyse",
    investigations: "Onderzoeken",
    newInvestigation: "Nieuw onderzoek",
    overview: "Overzicht",
    timeline: "Tijdlijn",
    failures: "Falen",
    causalTree: "Oorzakenboom",
    causes: "Oorzaken",
    rootCauses: "Grondoorzaken",
    events: "Gebeurtenissen",
    sequenceOfEvents: "Volgorde van gebeurtenissen",
    reconstructTimeline: "Reconstrueer de tijdlijn",
    addEvent: "Gebeurtenis toevoegen",
    noEvents: "Geen gebeurtenissen vastgelegd",
    startAddingEvents: "Begin met het toevoegen van de eerste gebeurtenis",
    failureIdentification: "Faalidentificatie",
    defineFailure: "Definieer wat technisch gefaald heeft",
    addFailure: "Falen toevoegen",
    noFailures: "Geen falen geïdentificeerd",
    documentFailure: "Documenteer wat gefaald heeft",
    buildCausalTree: "Bouw oorzaak-en-gevolg relaties",
    addCause: "Oorzaak toevoegen",
    noCauses: "Geen oorzaken geïdentificeerd",
    startBuildingTree: "Begin met het bouwen van de oorzakenboom",
    correctiveActions: "Corrigerende acties",
    trackActions: "Volg acties om herhaling te voorkomen",
    addAction: "Actie toevoegen",
    noActions: "Geen acties gedefinieerd",
    defineActions: "Definieer corrigerende acties",
    markAsRootCause: "Markeer als grondoorzaak",
    parent: "Ouder",
    confidence: "Vertrouwen",
    evidenceSource: "Bewijsbron",
    mechanism: "Mechanisme",
    subsystem: "Subsysteem",
    component: "Component",
    linkedRootCause: "Gekoppelde grondoorzaak",
    act: "Actie",
    lead: "Leider",
    incidentDate: "Incidentdatum",
    draft: "Concept",
  },
  
  // Actions page
  actionsPage: {
    title: "Acties",
    totalActions: "Totaal acties",
    pendingActions: "In behandeling",
    completedActions: "Voltooid",
    overdueActions: "Achterstallig",
    searchPlaceholder: "Zoek acties...",
    addAction: "Actie toevoegen",
    noActions: "Nog geen acties",
    noActionsDesc: "Acties verschijnen hier wanneer u aanbevelingen promoot van dreigingen of onderzoeken",
    source: "Bron",
    assignedTo: "Toegewezen aan",
    notStarted: "Niet gestart",
    completed: "Voltooid",
    filterByStatus: "Filter op status",
    allStatus: "Alle statussen",
  },
  
  // Library page
  library: {
    title: "Bibliotheek",
    failureModes: "Faalmodi",
    equipmentTypes: "Apparatuurtypen",
    totalModes: "Totaal modi",
    categories: "Categorieën",
    searchPlaceholder: "Zoek faalmodi...",
    addFailureMode: "Faalmodus toevoegen",
    addEquipmentType: "Type toevoegen",
    noFailureModes: "Geen faalmodi gevonden",
    linkedEquipmentTypes: "Gekoppelde apparatuurtypen",
    selectEquipmentTypes: "Selecteer apparatuurtypen...",
    discipline: "Discipline",
    mechanical: "Mechanisch",
    electrical: "Elektrisch",
    instrumentation: "Instrumentatie",
    process: "Proces",
    icon: "Icoon",
    isoClass: "ISO klasse",
    typeId: "Type ID (uniek)",
  },
  
  // Equipment Manager
  equipment: {
    title: "Apparatuurbeheer",
    hierarchy: "Hiërarchie",
    tree: "Boom",
    levels: "Niveaus",
    properties: "Eigenschappen",
    addInstallation: "Installatie toevoegen",
    addChild: "Kind toevoegen",
    importList: "Lijst importeren",
    searchPlaceholder: "Zoek naam, beschrijving, tag...",
    matches: "resultaten",
    noEquipment: "Geen apparatuur in hiërarchie",
    addFirstEquipment: "Voeg uw eerste installatie toe om te beginnen",
    selectNode: "Selecteer een item",
    selectNodeDesc: "Klik op een apparatuuritem om de eigenschappen te bekijken en bewerken",
    installation: "Installatie",
    plant: "Fabriek/Eenheid",
    section: "Sectie",
    equipmentUnit: "Apparatuureenheid",
    subunit: "Subeenheid",
    maintainableItem: "Onderhoudbaar item",
    tag: "Tag",
    criticality: "Kriticiteit",
    selectCriticality: "Selecteer kriticiteit...",
    safetyCritical: "Veiligheidskritiek",
    productionCritical: "Productiekritiek",
    noCriticality: "Geen kriticiteit toegewezen",
    clearCriticality: "Kriticiteit wissen",
    dragDropHint: "Sleep items om te herschikken of hiërarchie te wijzigen",
    unassigned: "Niet-toegewezen items",
  },
  
  // Chat
  chat: {
    title: "Dreiging melden",
    subtitle: "Beschrijf het probleem",
    placeholder: "Beschrijf het probleem...",
    welcomeMessage: "Hallo! Ik ben hier om u te helpen apparatuurdreigingen te melden. Beschrijf wat er gebeurt - noem de apparatuur en het probleem, en ik maak een dreigingsrecord voor u aan.",
    threatRecorded: "Dreiging succesvol vastgelegd.",
    attachPhoto: "Foto bijvoegen",
    voiceInput: "Spraakinvoer",
  },
  
  // Info dialog
  info: {
    title: "ThreatBase - Risicomethodologie",
    fmeaScoring: "FMEA Risicoscoring",
    fmeaDescription: "Risicoscores worden berekend met behulp van Failure Mode and Effects Analysis (FMEA) methodologie:",
    formula: "Risicoscore = (Ernst × Frequentie × Detectie) / 10",
    maxScore: "Maximale score: 100",
    severity: "Ernst (Impact)",
    safetyHazard: "Veiligheidsrisico",
    productionLoss: "Productieverlies",
    equipmentDamage: "Apparatuurschade",
    environmental: "Milieu",
    occurrence: "Frequentie (Voorkomen)",
    firstTime: "Eerste keer",
    rare: "Zeldzaam",
    occasional: "Af en toe",
    frequent: "Frequent",
    detection: "Detectie (Moeilijkheid)",
    easy: "Makkelijk",
    moderate: "Gemiddeld",
    difficult: "Moeilijk",
    riskLevels: "Risiconiveaus",
    criticalityMultipliers: "Kriticiteit vermenigvuldigers",
    criticalityDescription: "Risicoscores worden aangepast op basis van apparatuurkriticiteit:",
    quickTips: "Snelle tips",
    tip1: "Gebruik de + knop om nieuwe dreigingen te melden via chat",
    tip2: "Sleep apparatuur in de hiërarchie om te reorganiseren",
    tip3: "Klik op een dreiging om details te bekijken en onderzoeken te starten",
    tip4: "Gebruik de Oorzaakanalyse voor grondoorzaakanalyse",
    tip5: "Promoot aanbevelingen naar Acties voor tracking",
  },
  
  // Auth
  auth: {
    login: "Inloggen",
    register: "Registreren",
    email: "E-mail",
    password: "Wachtwoord",
    confirmPassword: "Bevestig wachtwoord",
    name: "Naam",
    loginTitle: "Welkom terug",
    loginSubtitle: "Log in op uw account",
    registerTitle: "Account aanmaken",
    registerSubtitle: "Begin met het beheren van apparatuurdreigingen",
    noAccount: "Heeft u geen account?",
    hasAccount: "Heeft u al een account?",
    signUp: "Registreren",
    signIn: "Inloggen",
  },
};

const translations = { en, nl };

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("threatbase_language");
    return saved || "en";
  });

  useEffect(() => {
    localStorage.setItem("threatbase_language", language);
  }, [language]);

  const t = (key) => {
    const keys = key.split(".");
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === "en" ? "nl" : "en");
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
