import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

// English translations
const en = {
  // Navigation
  nav: {
    dashboard: "Dashboard",
    threats: "Threats",
    causalEngine: "Causal Engine",
    actions: "Actions",
    library: "Library",
    equipmentManager: "Equipment Manager",
    settings: "Settings",
    logout: "Logout",
  },
  
  // Dashboard
  dashboard: {
    title: "Dashboard",
    subtitle: "Overview of your risk management status",
    overallHealth: "Overall System Health",
    excellent: "Excellent",
    good: "Good",
    needsAttention: "Needs Attention",
    critical: "Critical",
    openThreats: "Open Threats",
    criticalHighRisk: "Critical/High Risk",
    overdueActions: "Overdue Actions",
    totalThreats: "Total Threats",
    totalActions: "Total Actions",
    investigations: "Investigations",
    equipment: "Equipment",
    totalAssets: "total assets",
    threatResolution: "Threat Resolution",
    actionCompletion: "Action Completion",
    investigationProgress: "Investigation Progress",
    threatsByStatus: "Threats by Status",
    threatsByRisk: "Threats by Risk Level",
    actionsByStatus: "Actions by Status",
    actionsByPriority: "Actions by Priority",
    recentThreats: "Recent Threats",
    recentActions: "Recent Actions",
    recentInvestigations: "Recent Investigations",
    noThreats: "No threats recorded",
    noActions: "No actions recorded",
    noInvestigations: "No investigations started",
    threatsByEquipment: "Threats by Equipment Type",
    operational: "Operational",
    reliabilityPerformance: "Reliability Performance",
    reliabilitySubtitle: "Holistic view of reliability management across your asset hierarchy",
    items: "items",
    dimensionDetails: "Dimension Details",
    quickStats: "Quick Stats",
    addEquipmentFirst: "Add equipment to your hierarchy to see reliability scores",
  },
  
  // Common
  common: {
    search: "Search",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    update: "Update",
    create: "Create",
    close: "Close",
    loading: "Loading...",
    noResults: "No results found",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    all: "All",
    open: "Open",
    closed: "Closed",
    inProgress: "In Progress",
    status: "Status",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    critical: "Critical",
    name: "Name",
    description: "Description",
    date: "Date",
    time: "Time",
    comment: "Comment",
    comments: "Comments",
    evidence: "Evidence",
    owner: "Owner",
    dueDate: "Due Date",
    category: "Category",
    type: "Type",
    asset: "Asset",
    location: "Location",
    equipmentType: "Equipment Type",
    failureMode: "Failure Mode",
    enterName: "Enter name",
    creating: "Creating...",
    uploading: "Uploading...",
    parsing: "Parsing...",
    assign: "Assign",
    assigning: "Assigning...",
    add: "Add",
  },
  
  // Threats page
  threats: {
    title: "Threats",
    totalThreats: "Total Threats",
    openThreats: "Open Threats",
    highPriority: "High Priority",
    searchPlaceholder: "Search threats...",
    reportThreat: "Report Threat",
    noThreats: "No threats reported",
    noThreatsDesc: "Click the + button to report your first threat",
    riskScore: "Risk Score",
    riskLevel: "Risk Level",
    rank: "Rank",
    failureMode: "Failure Mode",
    equipmentType: "Equipment Type",
    impact: "Impact",
    frequency: "Frequency",
    likelihood: "Likelihood",
    detectability: "Detectability",
    recommendedActions: "Recommended Actions",
    viewDetails: "View full details",
    startInvestigation: "Start Investigation",
    editThreat: "Edit Threat",
    deleteThreat: "Delete Threat",
  },
  
  // Causal Engine
  causal: {
    title: "Causal Engine",
    investigations: "Investigations",
    newInvestigation: "New Investigation",
    overview: "Overview",
    timeline: "Timeline",
    failures: "Failures",
    causalTree: "Causal Tree",
    causes: "Causes",
    rootCauses: "Root Causes",
    events: "Events",
    sequenceOfEvents: "Sequence of Events",
    reconstructTimeline: "Reconstruct the timeline",
    addEvent: "Add Event",
    noEvents: "No events recorded",
    startAddingEvents: "Start by adding the first event",
    failureIdentification: "Failure Identification",
    defineFailure: "Define what technically failed",
    addFailure: "Add Failure",
    noFailures: "No failures identified",
    documentFailure: "Document what failed",
    buildCausalTree: "Build cause-and-effect relationships",
    addCause: "Add Cause",
    noCauses: "No causes identified",
    startBuildingTree: "Start building the causal tree",
    correctiveActions: "Corrective Actions",
    trackActions: "Track actions to prevent recurrence",
    addAction: "Add Action",
    noActions: "No actions defined",
    defineActions: "Define corrective actions",
    markAsRootCause: "Mark as Root Cause",
    parent: "Parent",
    confidence: "Confidence",
    evidenceSource: "Evidence Source",
    mechanism: "Mechanism",
    subsystem: "Subsystem",
    component: "Component",
    linkedRootCause: "Linked Root Cause",
    act: "Act",
    lead: "Lead",
    incidentDate: "Incident Date",
    draft: "Draft",
    searchInvestigations: "Search investigations...",
    noInvestigations: "No investigations yet",
    noInvestigationsDesc: "Start a new investigation to analyze equipment failures",
    editInvestigation: "Edit Investigation",
    deleteInvestigation: "Delete Investigation",
    editEvent: "Edit Event",
    editFailure: "Edit Failure",
    editCause: "Edit Cause",
    editAction: "Edit Action",
    caseNumber: "Case Number",
    openActions: "Open Actions",
    noActionsYet: "No corrective actions yet",
    defineActionsDesc: "Define actions to prevent recurrence",
    notes: "Notes",
    investigationNotes: "Investigation Notes",
    notesPlaceholder: "Add notes, observations, or important details about this investigation...",
    attachedFiles: "Attached Files",
    addFile: "Add File",
    noFilesYet: "No files attached yet",
    dropFilesHint: "Click 'Add File' to upload documents, images, or reports",
    filesUploaded: "File(s) uploaded successfully",
    uploadFailed: "Failed to upload file(s)",
    downloadFailed: "Failed to download file",
    fileDeleted: "File deleted",
    actionPromoted: "Action promoted! View it in the Actions tab.",
    actionPromoteFailed: "Failed to promote action",
    category: "Category",
    operationalEvent: "Operational Event",
    alarm: "Alarm",
    maintenanceAction: "Maintenance Action",
    humanDecision: "Human Decision",
    systemResponse: "System Response",
    environmental: "Environmental",
    selectCategory: "Select category",
    selectConfidence: "Select confidence level",
    degradationMechanism: "Degradation Mechanism",
    rootCause: "Root Cause",
    selectParent: "Select parent cause",
    noParent: "No parent (top-level)",
    technicalCause: "Technical Cause",
    humanCause: "Human/Organizational Cause",
    externalCause: "External Cause",
    designCause: "Design/Engineering Cause",
    selectStatus: "Select status",
    selectPriority: "Select priority",
    inProgress: "In Progress",
    underReview: "Under Review",
    completed: "Completed",
    selectLinkedCause: "Select linked cause",
  },
  
  // Actions page
  actionsPage: {
    title: "Actions",
    totalActions: "Total Actions",
    pendingActions: "Pending",
    completedActions: "Completed",
    overdueActions: "Overdue",
    searchPlaceholder: "Search actions...",
    addAction: "Add Action",
    noActions: "No actions yet",
    noActionsDesc: "Actions will appear here when you promote recommendations from threats or investigations",
    source: "Source",
    assignedTo: "Assigned To",
    notStarted: "Not Started",
    completed: "Completed",
    filterByStatus: "Filter by status",
    allStatus: "All Status",
    noSourceLinked: "No source linked",
    linkedToInvestigation: "Linked to Investigation",
    linkedToThreat: "Linked to Threat",
  },
  
  // Library page
  library: {
    title: "Library",
    failureModes: "Failure Modes",
    equipmentTypes: "Equipment Types",
    maintenance: "Maintenance",
    totalModes: "Total Modes",
    categories: "Categories",
    searchPlaceholder: "Search failure modes...",
    addFailureMode: "Add Failure Mode",
    addEquipmentType: "Add Type",
    editEquipmentType: "Edit Equipment Type",
    noFailureModes: "No failure modes found",
    noMatches: "No matches found",
    tryAdjusting: "Try adjusting your search or filters",
    linkedEquipmentTypes: "Linked Equipment Types",
    selectEquipmentTypes: "Select equipment types...",
    discipline: "Discipline",
    mechanical: "Mechanical",
    electrical: "Electrical",
    instrumentation: "Instrumentation",
    process: "Process",
    icon: "Icon",
    isoClass: "ISO Class",
    typeId: "Type ID (unique)",
    typesDefined: "types defined",
    severity: "Severity",
    occurrence: "Occurrence",
    detectability: "Detectability",
    keywords: "Keywords",
    addKeyword: "Add keyword and press Enter",
    recommendedActions: "Recommended Actions",
    addAction: "Add action and press Enter",
    allCategories: "All Categories",
    linked: "linked",
    selected: "Selected",
    types: "type(s)",
    editFailureMode: "Edit Failure Mode",
    addFailureModeDesc: "Create a new failure mode entry.",
    updateFailureModeDesc: "Update the failure mode details below.",
    category: "Category",
    equipment: "Equipment",
    equipmentPlaceholder: "e.g., Centrifugal Pump",
    failureModeName: "Failure Mode Name",
    clickToSelect: "Click to select/deselect (multiple allowed)",
    selectFailureMode: "Select a Failure Mode",
    selectFailureModeDesc: "Click on a failure mode from the list to view its details",
    riskScore: "Risk Score",
    linkedEquipmentTypes: "Linked Equipment Types",
    noLinkedTypes: "No equipment types linked",
    noRecommendedActions: "No recommended actions defined",
  },
  
  // Equipment Manager
  equipment: {
    title: "Equipment Manager",
    hierarchy: "Hierarchy",
    tree: "Tree",
    levels: "Levels",
    properties: "Properties",
    addInstallation: "Add Installation",
    addChild: "Add Child",
    importList: "Import List",
    searchPlaceholder: "Search name, description, tag...",
    matches: "matches",
    noEquipment: "No equipment in hierarchy",
    addFirstEquipment: "Add your first installation to get started",
    selectNode: "Select a node",
    selectNodeDesc: "Click on an equipment item to view and edit its properties",
    noSelection: "No Selection",
    selectFromHierarchy: "Select an item from the hierarchy to view properties",
    dragDropTips: "Drag & Drop Tips",
    dragTip1: "Drag items to reorder within siblings",
    dragTip2: "Drop on top/bottom edge to reorder",
    dragTip3: "Drop in center to make child",
    dragToReorder: "Drag to reorder or move",
    installation: "Installation",
    plant: "Plant/Unit",
    section: "Section/System",
    equipmentUnit: "Equipment Unit",
    subunit: "Subunit",
    maintainableItem: "Maintainable Item",
    tag: "Tag",
    criticality: "Criticality",
    selectCriticality: "Select criticality...",
    safetyCritical: "Safety Critical",
    productionCritical: "Production Critical",
    noCriticality: "No criticality assigned",
    clearCriticality: "Clear criticality",
    safetyImpact: "Safety",
    productionImpact: "Production",
    environmentalImpact: "Environmental",
    reputationImpact: "Reputation",
    overallCriticality: "Overall Criticality",
    dragDropHint: "Drag items to reorder or change hierarchy",
    unassigned: "Unassigned Items",
    dragToHierarchy: "Drag to hierarchy",
    importEquipmentList: "Import Equipment List",
    pasteEquipmentList: "Paste Equipment List",
    orUpload: "or",
    uploadFile: "Upload File",
    supportedFormats: "Supported: .txt, .csv, .xlsx, .xls, .pdf",
    parseList: "Parse List",
    riskScore: "Risk Score",
    equipmentType: "Equipment Type",
    discipline: "Discipline",
    autoAssigned: "Auto-assigned from equipment type",
    selectLevel: "Select Level",
    assignToHierarchy: "Assign to Hierarchy",
    assignUnder: "Assign under",
    demoteTo: "Demote to",
    selectNewParent: "Select a new parent",
    noValidParents: "No valid parent nodes found",
    createFirst: "first",
    moving: "Moving",
    clickTarget: "Click on a green highlighted target",
  },

  // Hierarchy context menu
  hierarchy: {
    addThreat: "Add Threat",
    rightClickHint: "Right-click for options",
  },
  
  // Chat
  chat: {
    title: "Report Threat",
    subtitle: "Describe the failure",
    placeholder: "Describe the issue...",
    welcomeMessage: "Hi! I'm here to help you report equipment threats. Just describe what's happening - mention the equipment and the problem, and I'll create a threat record for you.",
    threatRecorded: "Threat recorded successfully.",
    attachPhoto: "Attach photo",
    voiceInput: "Voice input",
  },
  
  // Info dialog
  info: {
    title: "ReliabilityOS - Risk Methodology",
    fmeaScoring: "FMEA Risk Scoring",
    fmeaDescription: "Risk scores are calculated using Failure Mode and Effects Analysis (FMEA) methodology:",
    formula: "Risk Score = (Severity × Occurrence × Detection) / 10",
    maxScore: "Maximum score: 100",
    severity: "Severity (Impact)",
    safetyHazard: "Safety Hazard",
    productionLoss: "Production Loss",
    equipmentDamage: "Equipment Damage",
    environmental: "Environmental",
    occurrence: "Occurrence (Frequency)",
    firstTime: "First Time",
    rare: "Rare",
    occasional: "Occasional",
    frequent: "Frequent",
    detection: "Detection (Difficulty)",
    easy: "Easy",
    moderate: "Moderate",
    difficult: "Difficult",
    riskLevels: "Risk Levels",
    criticalityDimensions: "4-Dimension Criticality Assessment",
    criticalityDimensionsDesc: "Equipment criticality is assessed across 4 independent dimensions, each rated 1-5:",
    safetyDimension: "Safety Impact",
    productionDimension: "Production Impact",
    environmentalDimension: "Environmental Impact",
    reputationDimension: "Reputation Impact",
    weight: "Weight",
    criticalityFormula: "Risk Score = (Safety×25) + (Production×20) + (Environmental×15) + (Reputation×10)",
    overallCriticalityDesc: "Overall Criticality = Maximum value across all 4 dimensions",
    quickTips: "Quick Tips",
    tip1: "Use the + button to report new threats via chat",
    tip2: "Drag and drop equipment in the hierarchy to reorganize",
    tip3: "Click on a threat to view details and start investigations",
    tip4: "Use the Causal Engine to perform root cause analysis",
    tip5: "Promote recommendations to Actions for tracking",
  },
  
  // Auth
  auth: {
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    name: "Name",
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your account",
    registerTitle: "Create account",
    registerSubtitle: "Start managing equipment threats",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    signUp: "Sign up",
    signIn: "Sign in",
  },

  // AI Features
  ai: {
    riskAnalysis: "AI Risk Analysis",
    causalIntelligence: "Causal Intelligence",
    analyzeWithAi: "Analyze with AI",
    analyzing: "Analyzing...",
    whyIsThisHappening: "Why is this happening?",
    analyzingCauses: "Analyzing causes...",
    riskScore: "Risk Score",
    failureProbability: "Failure Probability",
    timeToFailure: "Time to Failure",
    trendChange: "Trend Change",
    keyRiskFactors: "Key Risk Factors",
    riskForecast: "Risk Forecast",
    keyInsights: "Key Insights",
    aiRecommendations: "AI Recommendations",
    lastAnalyzed: "Last analyzed",
    probableCauses: "Probable Causes",
    rankedByLikelihood: "ranked by likelihood",
    supportingEvidence: "Supporting Evidence",
    recommendedMitigations: "Recommended Mitigations",
    contributingFactors: "Contributing Factors",
    analysisConfidence: "Analysis confidence",
    startInvestigationWithAi: "Start Investigation with AI Insights",
    creatingInvestigation: "Creating Investigation...",
    addAsAction: "Add as action",
    addedAsAction: "Added as action",
    actionCreated: "Action created from AI recommendation!",
    addToThreat: "Add to threat recommendations",
    alreadyAdded: "Already added",
    recommendationAdded: "Recommendation added to threat!",
    recommendationExists: "Recommendation already exists",
    recommendationFailed: "Failed to add recommendation",
    investigationCreated: "Investigation created with AI insights!",
    increasing: "Increasing",
    stable: "Stable",
    decreasing: "Decreasing",
    highConfidence: "High confidence",
    mediumConfidence: "Medium confidence",
    lowConfidence: "Low confidence",
    veryLikely: "Very Likely",
    likely: "Likely",
    possible: "Possible",
    unlikely: "Unlikely",
    technicalCause: "Technical",
    humanFactor: "Human Factor",
    maintenanceIssue: "Maintenance",
    designIssue: "Design Issue",
    organizationalFactor: "Organizational",
    externalCondition: "External",
    causesIdentified: "probable causes identified",
    unknown: "Unknown",
    missingLibraryData: "Missing Library Data",
    missingLibraryDataDesc: "The following items are not in your library. Add them for better AI analysis accuracy:",
    goToLibrary: "Go to Library",
  },

  // Threat Detail
  threatDetail: {
    title: "Threat Details",
    backToThreats: "Back to Threats",
    riskScoreCard: "Risk Score",
    threatInfo: "Threat Information",
    equipmentInfo: "Equipment Information",
    causeAnalysis: "Cause Analysis",
    recommendedActions: "Recommended Actions",
    addAction: "Add Action",
    createAction: "Create Action",
    actionTitle: "Title",
    actionDescription: "Description",
    actionPriority: "Priority",
    actionAssignee: "Assignee",
    actionDueDate: "Due Date",
    deleteConfirm: "Are you sure?",
    deleteWarning: "This will permanently delete this threat and all associated data.",
    mitigated: "Mitigated",
    createdAt: "Created",
  },

  // Maintenance Strategies
  maintenance: {
    title: "Maintenance Strategies",
    subtitle: "AI-generated maintenance plans by equipment type",
    generateStrategy: "Generate Strategy",
    generateAll: "Generate All",
    generating: "Generating...",
    noStrategies: "No maintenance strategies yet",
    noStrategiesDesc: "Generate maintenance strategies for your equipment types",
    selectEquipmentType: "Select Equipment Type",
    operatorRounds: "Operator Rounds",
    detectionSystems: "Detection Systems",
    scheduledMaintenance: "Scheduled Maintenance",
    correctiveActions: "Corrective Actions",
    emergencyProcedures: "Emergency Procedures",
    spareParts: "Spare Parts",
    safetyCritical: "Safety Critical",
    productionCritical: "Production Critical",
    frequency: "Frequency",
    discipline: "Discipline",
    resources: "Resources",
    duration: "Duration",
    detects: "Detects",
    prevents: "Prevents",
    addresses: "Addresses",
    checksFor: "Checks for",
    sensor: "sensor",
    sensors: "sensors",
    task: "task",
    tasks: "tasks",
    action: "action",
    round: "round",
    rounds: "rounds",
    procedure: "procedure",
    procedures: "procedures",
    part: "part",
    parts: "parts",
    deleteStrategy: "Delete Strategy?",
    deleteStrategyDesc: "This will permanently delete the maintenance strategy for",
    allCriticalityLevels: "all criticality levels",
    autoGenerated: "Auto-generated from FMEA",
    criticalityLevels: "criticality levels",
    editItem: "Edit Item",
    addItem: "Add Item",
    itemName: "Item Name",
    checklistItems: "Checklist Items",
    failureModesAddressed: "Failure Modes Addressed",
    failureModesDetected: "Failure Modes Detected",
    sensorType: "Sensor Type",
    alertThreshold: "Alert Threshold",
    alarmThreshold: "Alarm Threshold",
    tripThreshold: "Trip Threshold",
    partNumber: "Part Number",
    quantity: "Quantity",
    minStock: "Min Stock",
    leadTime: "Lead Time",
    estimatedCost: "Estimated Cost",
    triggerConditions: "Trigger Conditions",
    immediateActions: "Immediate Actions",
    notificationList: "Notification List",
  },

  // Reliability Performance
  reliability: {
    title: "Reliability Performance",
    subtitle: "Holistic view of reliability management across your asset hierarchy",
    overallScore: "Overall Score",
    equipmentHealth: "Equipment Health",
    dimensionBreakdown: "Dimension Breakdown",
    criticalityDimension: "Criticality",
    incidentsDimension: "Incidents",
    investigationsDimension: "Investigations",
    maintenanceDimension: "Maintenance",
    reactionsDimension: "Reactions",
    threatsDimension: "Threats",
    withCriticality: "With Criticality",
    openThreats: "Open Threats",
    totalInvestigations: "Investigations",
    totalActions: "Total Actions",
    filterByLevel: "Filter by Level",
    allLevels: "All Levels",
    searchEquipment: "Search equipment...",
    noEquipment: "No equipment found",
    addEquipmentToSee: "Add equipment to your hierarchy to see reliability scores",
    frameworkInfo: "Framework Methodology",
    frameworkDescription: "The reliability performance score is calculated across 6 dimensions:",
    criticalityDesc: "Equipment hierarchy completeness and criticality assignments",
    incidentsDesc: "Incident records and positive validation",
    investigationsDesc: "Cross-asset analysis coverage",
    maintenanceDesc: "Active maintenance plans and spares",
    reactionsDesc: "Clear reaction plans (resources, support, downtime)",
    threatsDesc: "Unmitigated threat management",
    good: "Good",
    fair: "Fair",
    poor: "Poor",
    crit: "Crit",
    maint: "Maint",
  },
};

// Dutch translations
const nl = {
  // Navigation
  nav: {
    dashboard: "Dashboard",
    threats: "Dreigingen",
    causalEngine: "Oorzaakanalyse",
    actions: "Acties",
    library: "Bibliotheek",
    equipmentManager: "Apparatuurbeheer",
    settings: "Instellingen",
    logout: "Uitloggen",
  },
  
  // Dashboard
  dashboard: {
    title: "Dashboard",
    subtitle: "Overzicht van uw risicobeheer status",
    overallHealth: "Algemene Systeemgezondheid",
    excellent: "Uitstekend",
    good: "Goed",
    needsAttention: "Aandacht nodig",
    critical: "Kritiek",
    openThreats: "Open dreigingen",
    criticalHighRisk: "Kritiek/Hoog risico",
    overdueActions: "Achterstallige acties",
    totalThreats: "Totaal dreigingen",
    totalActions: "Totaal acties",
    investigations: "Onderzoeken",
    equipment: "Apparatuur",
    totalAssets: "totale assets",
    threatResolution: "Dreigingsoplossing",
    actionCompletion: "Actie-afronding",
    investigationProgress: "Onderzoeksvoortgang",
    threatsByStatus: "Dreigingen per status",
    threatsByRisk: "Dreigingen per risiconiveau",
    actionsByStatus: "Acties per status",
    actionsByPriority: "Acties per prioriteit",
    recentThreats: "Recente dreigingen",
    recentActions: "Recente acties",
    recentInvestigations: "Recente onderzoeken",
    noThreats: "Geen dreigingen geregistreerd",
    noActions: "Geen acties geregistreerd",
    noInvestigations: "Geen onderzoeken gestart",
    threatsByEquipment: "Dreigingen per apparaattype",
    operational: "Operationeel",
    reliabilityPerformance: "Betrouwbaarheidsprestaties",
    reliabilitySubtitle: "Holistisch overzicht van betrouwbaarheidsbeheer over uw assethiërarchie",
    items: "items",
    dimensionDetails: "Dimensie details",
    quickStats: "Snelle statistieken",
    addEquipmentFirst: "Voeg apparatuur toe aan uw hiërarchie om betrouwbaarheidsscores te zien",
  },
  
  // Common
  common: {
    search: "Zoeken",
    add: "Toevoegen",
    edit: "Bewerken",
    delete: "Verwijderen",
    cancel: "Annuleren",
    save: "Opslaan",
    update: "Bijwerken",
    create: "Aanmaken",
    close: "Sluiten",
    loading: "Laden...",
    noResults: "Geen resultaten gevonden",
    confirm: "Bevestigen",
    yes: "Ja",
    no: "Nee",
    all: "Alle",
    open: "Open",
    closed: "Gesloten",
    inProgress: "In uitvoering",
    status: "Status",
    priority: "Prioriteit",
    high: "Hoog",
    medium: "Gemiddeld",
    low: "Laag",
    critical: "Kritiek",
    name: "Naam",
    description: "Beschrijving",
    date: "Datum",
    time: "Tijd",
    comment: "Opmerking",
    comments: "Opmerkingen",
    evidence: "Bewijs",
    owner: "Eigenaar",
    dueDate: "Vervaldatum",
    category: "Categorie",
    type: "Type",
    asset: "Asset",
    location: "Locatie",
    equipmentType: "Apparatuurtype",
    failureMode: "Faalmodus",
    enterName: "Voer naam in",
    creating: "Aanmaken...",
    uploading: "Uploaden...",
    parsing: "Verwerken...",
    assign: "Toewijzen",
    assigning: "Toewijzen...",
  },
  
  // Threats page
  threats: {
    title: "Dreigingen",
    totalThreats: "Totaal dreigingen",
    openThreats: "Open dreigingen",
    highPriority: "Hoge prioriteit",
    searchPlaceholder: "Zoek dreigingen...",
    reportThreat: "Dreiging melden",
    noThreats: "Geen dreigingen gemeld",
    noThreatsDesc: "Klik op de + knop om uw eerste dreiging te melden",
    riskScore: "Risicoscore",
    riskLevel: "Risiconiveau",
    rank: "Rang",
    failureMode: "Faalmodus",
    equipmentType: "Apparatuurtype",
    impact: "Impact",
    frequency: "Frequentie",
    likelihood: "Waarschijnlijkheid",
    detectability: "Detecteerbaarheid",
    recommendedActions: "Aanbevolen acties",
    viewDetails: "Bekijk details",
    startInvestigation: "Start onderzoek",
    editThreat: "Bewerk dreiging",
    deleteThreat: "Verwijder dreiging",
  },
  
  // Causal Engine
  causal: {
    title: "Oorzaakanalyse",
    investigations: "Onderzoeken",
    newInvestigation: "Nieuw onderzoek",
    overview: "Overzicht",
    timeline: "Tijdlijn",
    failures: "Falen",
    causalTree: "Oorzakenboom",
    causes: "Oorzaken",
    rootCauses: "Grondoorzaken",
    events: "Gebeurtenissen",
    sequenceOfEvents: "Volgorde van gebeurtenissen",
    reconstructTimeline: "Reconstrueer de tijdlijn",
    addEvent: "Gebeurtenis toevoegen",
    noEvents: "Geen gebeurtenissen vastgelegd",
    startAddingEvents: "Begin met het toevoegen van de eerste gebeurtenis",
    failureIdentification: "Faalidentificatie",
    defineFailure: "Definieer wat technisch gefaald heeft",
    addFailure: "Falen toevoegen",
    noFailures: "Geen falen geïdentificeerd",
    documentFailure: "Documenteer wat gefaald heeft",
    buildCausalTree: "Bouw oorzaak-en-gevolg relaties",
    addCause: "Oorzaak toevoegen",
    noCauses: "Geen oorzaken geïdentificeerd",
    startBuildingTree: "Begin met het bouwen van de oorzakenboom",
    correctiveActions: "Corrigerende acties",
    trackActions: "Volg acties om herhaling te voorkomen",
    addAction: "Actie toevoegen",
    noActions: "Geen acties gedefinieerd",
    defineActions: "Definieer corrigerende acties",
    markAsRootCause: "Markeer als grondoorzaak",
    parent: "Ouder",
    confidence: "Vertrouwen",
    evidenceSource: "Bewijsbron",
    mechanism: "Mechanisme",
    subsystem: "Subsysteem",
    component: "Component",
    linkedRootCause: "Gekoppelde grondoorzaak",
    act: "Actie",
    lead: "Leider",
    incidentDate: "Incidentdatum",
    draft: "Concept",
    searchInvestigations: "Zoek onderzoeken...",
    noInvestigations: "Nog geen onderzoeken",
    noInvestigationsDesc: "Start een nieuw onderzoek om apparatuurstoringen te analyseren",
    editInvestigation: "Onderzoek bewerken",
    deleteInvestigation: "Onderzoek verwijderen",
    editEvent: "Gebeurtenis bewerken",
    editFailure: "Falen bewerken",
    editCause: "Oorzaak bewerken",
    editAction: "Actie bewerken",
    caseNumber: "Zaaknummer",
    openActions: "Open acties",
    noActionsYet: "Nog geen corrigerende acties",
    defineActionsDesc: "Definieer acties om herhaling te voorkomen",
    notes: "Notities",
    investigationNotes: "Onderzoeksnotities",
    notesPlaceholder: "Voeg notities, observaties of belangrijke details over dit onderzoek toe...",
    attachedFiles: "Bijgevoegde bestanden",
    addFile: "Bestand toevoegen",
    noFilesYet: "Nog geen bestanden bijgevoegd",
    dropFilesHint: "Klik op 'Bestand toevoegen' om documenten, afbeeldingen of rapporten te uploaden",
    filesUploaded: "Bestand(en) succesvol geüpload",
    uploadFailed: "Uploaden van bestand(en) mislukt",
    downloadFailed: "Downloaden van bestand mislukt",
    fileDeleted: "Bestand verwijderd",
    actionPromoted: "Actie gepromoveerd! Bekijk het in het Acties tabblad.",
    actionPromoteFailed: "Actie promoveren mislukt",
    category: "Categorie",
    operationalEvent: "Operationele gebeurtenis",
    alarm: "Alarm",
    maintenanceAction: "Onderhoudsactie",
    humanDecision: "Menselijke beslissing",
    systemResponse: "Systeemreactie",
    environmental: "Omgevingsfactor",
    selectCategory: "Selecteer categorie",
    selectConfidence: "Selecteer betrouwbaarheidsniveau",
    degradationMechanism: "Degradatiemechanisme",
    rootCause: "Grondoorzaak",
    selectParent: "Selecteer bovenliggende oorzaak",
    noParent: "Geen ouder (top-niveau)",
    technicalCause: "Technische oorzaak",
    humanCause: "Menselijke/Organisatorische oorzaak",
    externalCause: "Externe oorzaak",
    designCause: "Ontwerp/Engineering oorzaak",
    selectStatus: "Selecteer status",
    selectPriority: "Selecteer prioriteit",
    inProgress: "In uitvoering",
    underReview: "In beoordeling",
    completed: "Voltooid",
    selectLinkedCause: "Selecteer gekoppelde oorzaak",
  },
  
  // Actions page
  actionsPage: {
    title: "Acties",
    totalActions: "Totaal acties",
    pendingActions: "In behandeling",
    completedActions: "Voltooid",
    overdueActions: "Achterstallig",
    searchPlaceholder: "Zoek acties...",
    addAction: "Actie toevoegen",
    noActions: "Nog geen acties",
    noActionsDesc: "Acties verschijnen hier wanneer u aanbevelingen promoot van dreigingen of onderzoeken",
    source: "Bron",
    assignedTo: "Toegewezen aan",
    notStarted: "Niet gestart",
    completed: "Voltooid",
    filterByStatus: "Filter op status",
    allStatus: "Alle statussen",
    noSourceLinked: "Geen bron gekoppeld",
    linkedToInvestigation: "Gekoppeld aan onderzoek",
    linkedToThreat: "Gekoppeld aan dreiging",
  },
  
  // Library page
  library: {
    title: "Bibliotheek",
    failureModes: "Faalmodi",
    equipmentTypes: "Apparatuurtypen",
    maintenance: "Onderhoud",
    totalModes: "Totaal modi",
    categories: "Categorieën",
    searchPlaceholder: "Zoek faalmodi...",
    addFailureMode: "Faalmodus toevoegen",
    addEquipmentType: "Type toevoegen",
    editEquipmentType: "Apparatuurtype bewerken",
    noFailureModes: "Geen faalmodi gevonden",
    noMatches: "Geen overeenkomsten gevonden",
    tryAdjusting: "Probeer uw zoekopdracht of filters aan te passen",
    linkedEquipmentTypes: "Gekoppelde apparatuurtypen",
    selectEquipmentTypes: "Selecteer apparatuurtypen...",
    discipline: "Discipline",
    mechanical: "Mechanisch",
    electrical: "Elektrisch",
    instrumentation: "Instrumentatie",
    process: "Proces",
    icon: "Icoon",
    isoClass: "ISO klasse",
    typeId: "Type ID (uniek)",
    typesDefined: "typen gedefinieerd",
    severity: "Ernst",
    occurrence: "Frequentie",
    detectability: "Detecteerbaarheid",
    keywords: "Trefwoorden",
    addKeyword: "Voeg trefwoord toe en druk op Enter",
    recommendedActions: "Aanbevolen acties",
    addAction: "Voeg actie toe en druk op Enter",
    allCategories: "Alle categorieën",
    linked: "gekoppeld",
    selected: "Geselecteerd",
    types: "type(s)",
    editFailureMode: "Faalmodus bewerken",
    addFailureModeDesc: "Maak een nieuwe faalmodus aan.",
    updateFailureModeDesc: "Werk de faalmodus details hieronder bij.",
    category: "Categorie",
    equipment: "Apparatuur",
    equipmentPlaceholder: "bijv., Centrifugaalpomp",
    failureModeName: "Faalmodus naam",
    clickToSelect: "Klik om te selecteren/deselecteren (meerdere mogelijk)",
    selectFailureMode: "Selecteer een Faalmodus",
    selectFailureModeDesc: "Klik op een faalmodus in de lijst om de details te bekijken",
    riskScore: "Risicoscore",
    linkedEquipmentTypes: "Gekoppelde apparatuurtypen",
    noLinkedTypes: "Geen apparatuurtypen gekoppeld",
    noRecommendedActions: "Geen aanbevolen acties gedefinieerd",
  },
  
  // Equipment Manager
  equipment: {
    title: "Apparatuurbeheer",
    hierarchy: "Hiërarchie",
    tree: "Boom",
    levels: "Niveaus",
    properties: "Eigenschappen",
    addInstallation: "Installatie toevoegen",
    addChild: "Kind toevoegen",
    importList: "Lijst importeren",
    searchPlaceholder: "Zoek naam, beschrijving, tag...",
    matches: "resultaten",
    noEquipment: "Geen apparatuur in hiërarchie",
    addFirstEquipment: "Voeg uw eerste installatie toe om te beginnen",
    selectNode: "Selecteer een item",
    selectNodeDesc: "Klik op een apparatuuritem om de eigenschappen te bekijken en bewerken",
    installation: "Installatie",
    plant: "Fabriek/Eenheid",
    section: "Sectie",
    equipmentUnit: "Apparatuureenheid",
    subunit: "Subeenheid",
    maintainableItem: "Onderhoudbaar item",
    tag: "Tag",
    criticality: "Kriticiteit",
    selectCriticality: "Selecteer kriticiteit...",
    safetyCritical: "Veiligheidskritiek",
    productionCritical: "Productiekritiek",
    noCriticality: "Geen kriticiteit toegewezen",
    clearCriticality: "Kriticiteit wissen",
    safetyImpact: "Veiligheid",
    productionImpact: "Productie",
    environmentalImpact: "Milieu",
    reputationImpact: "Reputatie",
    overallCriticality: "Totale Kriticiteit",
    dragDropHint: "Sleep items om te herschikken of hiërarchie te wijzigen",
    unassigned: "Niet-toegewezen items",
    noSelection: "Geen selectie",
    selectFromHierarchy: "Selecteer een item uit de hiërarchie om eigenschappen te bekijken",
    dragDropTips: "Sleep & Laat Tips",
    dragTip1: "Sleep items om binnen gelijken te herschikken",
    dragTip2: "Laat vallen op boven/onderrand om te herschikken",
    dragTip3: "Laat vallen in midden om kind te maken",
    dragToReorder: "Sleep om te herschikken of te verplaatsen",
    section: "Sectie/Systeem",
    dragToHierarchy: "Sleep naar hiërarchie",
    importEquipmentList: "Apparatuurlijst importeren",
    pasteEquipmentList: "Apparatuurlijst plakken",
    orUpload: "of",
    uploadFile: "Bestand uploaden",
    supportedFormats: "Ondersteund: .txt, .csv, .xlsx, .xls, .pdf",
    parseList: "Lijst verwerken",
    riskScore: "Risicoscore",
    equipmentType: "Apparatuurtype",
    discipline: "Discipline",
    autoAssigned: "Automatisch toegewezen van apparatuurtype",
    selectLevel: "Selecteer niveau",
    assignToHierarchy: "Toewijzen aan hiërarchie",
    assignUnder: "Toewijzen onder",
    demoteTo: "Degraderen naar",
    selectNewParent: "Selecteer een nieuwe ouder",
    noValidParents: "Geen geldige ouder items gevonden",
    createFirst: "eerst",
    moving: "Verplaatsen",
    clickTarget: "Klik op een groen gemarkeerd doel",
  },

  // Hierarchy context menu
  hierarchy: {
    addThreat: "Dreiging toevoegen",
    rightClickHint: "Rechtsklik voor opties",
  },
  
  // Chat
  chat: {
    title: "Dreiging melden",
    subtitle: "Beschrijf het probleem",
    placeholder: "Beschrijf het probleem...",
    welcomeMessage: "Hallo! Ik ben hier om u te helpen apparatuurdreigingen te melden. Beschrijf wat er gebeurt - noem de apparatuur en het probleem, en ik maak een dreigingsrecord voor u aan.",
    threatRecorded: "Dreiging succesvol vastgelegd.",
    attachPhoto: "Foto bijvoegen",
    voiceInput: "Spraakinvoer",
  },
  
  // Info dialog
  info: {
    title: "ReliabilityOS - Risicomethodologie",
    fmeaScoring: "FMEA Risicoscoring",
    fmeaDescription: "Risicoscores worden berekend met behulp van Failure Mode and Effects Analysis (FMEA) methodologie:",
    formula: "Risicoscore = (Ernst × Frequentie × Detectie) / 10",
    maxScore: "Maximale score: 100",
    severity: "Ernst (Impact)",
    safetyHazard: "Veiligheidsrisico",
    productionLoss: "Productieverlies",
    equipmentDamage: "Apparatuurschade",
    environmental: "Milieu",
    occurrence: "Frequentie (Voorkomen)",
    firstTime: "Eerste keer",
    rare: "Zeldzaam",
    occasional: "Af en toe",
    frequent: "Frequent",
    detection: "Detectie (Moeilijkheid)",
    easy: "Makkelijk",
    moderate: "Gemiddeld",
    difficult: "Moeilijk",
    riskLevels: "Risiconiveaus",
    criticalityDimensions: "4-Dimensie Kriticiteitsbeoordeling",
    criticalityDimensionsDesc: "Apparatuurkriticiteit wordt beoordeeld over 4 onafhankelijke dimensies, elk beoordeeld 1-5:",
    safetyDimension: "Veiligheidsimpact",
    productionDimension: "Productie-impact",
    environmentalDimension: "Milieu-impact",
    reputationDimension: "Reputatie-impact",
    weight: "Gewicht",
    criticalityFormula: "Risicoscore = (Veiligheid×25) + (Productie×20) + (Milieu×15) + (Reputatie×10)",
    overallCriticalityDesc: "Totale Kriticiteit = Maximum waarde over alle 4 dimensies",
    quickTips: "Snelle tips",
    tip1: "Gebruik de + knop om nieuwe dreigingen te melden via chat",
    tip2: "Sleep apparatuur in de hiërarchie om te reorganiseren",
    tip3: "Klik op een dreiging om details te bekijken en onderzoeken te starten",
    tip4: "Gebruik de Oorzaakanalyse voor grondoorzaakanalyse",
    tip5: "Promoot aanbevelingen naar Acties voor tracking",
  },
  
  // Auth
  auth: {
    login: "Inloggen",
    register: "Registreren",
    email: "E-mail",
    password: "Wachtwoord",
    confirmPassword: "Bevestig wachtwoord",
    name: "Naam",
    loginTitle: "Welkom terug",
    loginSubtitle: "Log in op uw account",
    registerTitle: "Account aanmaken",
    registerSubtitle: "Begin met het beheren van apparatuurdreigingen",
    noAccount: "Heeft u geen account?",
    hasAccount: "Heeft u al een account?",
    signUp: "Registreren",
    signIn: "Inloggen",
  },

  // AI Features
  ai: {
    riskAnalysis: "AI Risicoanalyse",
    causalIntelligence: "Causale Intelligentie",
    analyzeWithAi: "Analyseer met AI",
    analyzing: "Analyseren...",
    whyIsThisHappening: "Waarom gebeurt dit?",
    analyzingCauses: "Oorzaken analyseren...",
    riskScore: "Risicoscore",
    failureProbability: "Faalkans",
    timeToFailure: "Tijd tot falen",
    trendChange: "Trendwijziging",
    keyRiskFactors: "Belangrijkste risicofactoren",
    riskForecast: "Risicovoorspelling",
    keyInsights: "Belangrijkste inzichten",
    aiRecommendations: "AI Aanbevelingen",
    lastAnalyzed: "Laatst geanalyseerd",
    probableCauses: "Waarschijnlijke oorzaken",
    rankedByLikelihood: "gerangschikt op waarschijnlijkheid",
    supportingEvidence: "Ondersteunend bewijs",
    recommendedMitigations: "Aanbevolen maatregelen",
    contributingFactors: "Bijdragende factoren",
    analysisConfidence: "Analyse betrouwbaarheid",
    startInvestigationWithAi: "Start onderzoek met AI inzichten",
    creatingInvestigation: "Onderzoek aanmaken...",
    addAsAction: "Toevoegen als actie",
    addedAsAction: "Toegevoegd als actie",
    actionCreated: "Actie aangemaakt vanuit AI aanbeveling!",
    addToThreat: "Toevoegen aan dreigingsaanbevelingen",
    alreadyAdded: "Reeds toegevoegd",
    recommendationAdded: "Aanbeveling toegevoegd aan dreiging!",
    recommendationExists: "Aanbeveling bestaat al",
    recommendationFailed: "Aanbeveling toevoegen mislukt",
    investigationCreated: "Onderzoek aangemaakt met AI inzichten!",
    increasing: "Stijgend",
    stable: "Stabiel",
    decreasing: "Dalend",
    highConfidence: "Hoge betrouwbaarheid",
    mediumConfidence: "Gemiddelde betrouwbaarheid",
    lowConfidence: "Lage betrouwbaarheid",
    veryLikely: "Zeer waarschijnlijk",
    likely: "Waarschijnlijk",
    possible: "Mogelijk",
    unlikely: "Onwaarschijnlijk",
    technicalCause: "Technisch",
    humanFactor: "Menselijke factor",
    maintenanceIssue: "Onderhoud",
    designIssue: "Ontwerpprobleem",
    organizationalFactor: "Organisatorisch",
    externalCondition: "Extern",
    causesIdentified: "waarschijnlijke oorzaken geïdentificeerd",
    unknown: "Onbekend",
    missingLibraryData: "Ontbrekende bibliotheekgegevens",
    missingLibraryDataDesc: "De volgende items ontbreken in uw bibliotheek. Voeg ze toe voor betere AI-analyse nauwkeurigheid:",
    goToLibrary: "Ga naar bibliotheek",
  },

  // Threat Detail
  threatDetail: {
    title: "Dreigingsdetails",
    backToThreats: "Terug naar dreigingen",
    riskScoreCard: "Risicoscore",
    threatInfo: "Dreigingsinformatie",
    equipmentInfo: "Apparatuurinformatie",
    causeAnalysis: "Oorzaakanalyse",
    recommendedActions: "Aanbevolen acties",
    addAction: "Actie toevoegen",
    createAction: "Actie aanmaken",
    actionTitle: "Titel",
    actionDescription: "Beschrijving",
    actionPriority: "Prioriteit",
    actionAssignee: "Toegewezen aan",
    actionDueDate: "Vervaldatum",
    deleteConfirm: "Weet u het zeker?",
    deleteWarning: "Dit verwijdert deze dreiging en alle bijbehorende gegevens permanent.",
    mitigated: "Gemitigeerd",
    createdAt: "Aangemaakt",
  },

  // Maintenance Strategies
  maintenance: {
    title: "Onderhoudsstrategieën",
    subtitle: "AI-gegenereerde onderhoudsplannen per apparatuurtype",
    generateStrategy: "Strategie genereren",
    generateAll: "Alles genereren",
    generating: "Genereren...",
    noStrategies: "Nog geen onderhoudsstrategieën",
    noStrategiesDesc: "Genereer onderhoudsstrategieën voor uw apparatuurtypen",
    selectEquipmentType: "Selecteer apparatuurtype",
    operatorRounds: "Operatorronden",
    detectionSystems: "Detectiesystemen",
    scheduledMaintenance: "Gepland onderhoud",
    correctiveActions: "Corrigerende acties",
    emergencyProcedures: "Noodprocedures",
    spareParts: "Reserveonderdelen",
    safetyCritical: "Veiligheidskritiek",
    productionCritical: "Productiekritiek",
    frequency: "Frequentie",
    discipline: "Discipline",
    resources: "Middelen",
    duration: "Duur",
    detects: "Detecteert",
    prevents: "Voorkomt",
    addresses: "Adresseert",
    checksFor: "Controleert op",
    sensor: "sensor",
    sensors: "sensoren",
    task: "taak",
    tasks: "taken",
    action: "actie",
    round: "ronde",
    rounds: "rondes",
    procedure: "procedure",
    procedures: "procedures",
    part: "onderdeel",
    parts: "onderdelen",
    deleteStrategy: "Strategie verwijderen?",
    deleteStrategyDesc: "Dit verwijdert permanent de onderhoudsstrategie voor",
    allCriticalityLevels: "alle kriticiteitsniveaus",
    autoGenerated: "Automatisch gegenereerd vanuit FMEA",
    criticalityLevels: "kriticiteitsniveaus",
    editItem: "Item bewerken",
    addItem: "Item toevoegen",
    itemName: "Itemnaam",
    checklistItems: "Checklistitems",
    failureModesAddressed: "Aangepakte faalmodi",
    failureModesDetected: "Gedetecteerde faalmodi",
    sensorType: "Sensortype",
    alertThreshold: "Waarschuwingsdrempel",
    alarmThreshold: "Alarmdrempel",
    tripThreshold: "Uitschakeldrempel",
    partNumber: "Onderdeelnummer",
    quantity: "Hoeveelheid",
    minStock: "Min. voorraad",
    leadTime: "Levertijd",
    estimatedCost: "Geschatte kosten",
    triggerConditions: "Triggercondities",
    immediateActions: "Onmiddellijke acties",
    notificationList: "Notificatielijst",
  },

  // Reliability Performance
  reliability: {
    title: "Betrouwbaarheidsprestaties",
    subtitle: "Holistisch overzicht van betrouwbaarheidsbeheer over uw assethiërarchie",
    overallScore: "Totaalscore",
    equipmentHealth: "Apparatuurgezondhied",
    dimensionBreakdown: "Dimensie-uitsplitsing",
    criticalityDimension: "Kriticiteit",
    incidentsDimension: "Incidenten",
    investigationsDimension: "Onderzoeken",
    maintenanceDimension: "Onderhoud",
    reactionsDimension: "Reacties",
    threatsDimension: "Dreigingen",
    withCriticality: "Met kriticiteit",
    openThreats: "Open dreigingen",
    totalInvestigations: "Onderzoeken",
    totalActions: "Totaal acties",
    filterByLevel: "Filter op niveau",
    allLevels: "Alle niveaus",
    searchEquipment: "Zoek apparatuur...",
    noEquipment: "Geen apparatuur gevonden",
    addEquipmentToSee: "Voeg apparatuur toe aan uw hiërarchie om betrouwbaarheidsscores te zien",
    frameworkInfo: "Framework methodologie",
    frameworkDescription: "De betrouwbaarheidsprestatie score wordt berekend over 6 dimensies:",
    criticalityDesc: "Apparatuurhiërarchie volledigheid en kriticiteitstoewijzingen",
    incidentsDesc: "Incidentenregistraties en positieve validatie",
    investigationsDesc: "Cross-asset analyse dekking",
    maintenanceDesc: "Actieve onderhoudsplannen en reserveonderdelen",
    reactionsDesc: "Duidelijke reactieplannen (middelen, ondersteuning, stilstand)",
    threatsDesc: "Niet-gemitigeerd dreigingsbeheer",
    good: "Goed",
    fair: "Redelijk",
    poor: "Slecht",
    crit: "Krit",
    maint: "Onderh",
  },
};

const translations = { en, nl };

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("reliabilityos_language");
    return saved || "en";
  });

  useEffect(() => {
    localStorage.setItem("reliabilityos_language", language);
  }, [language]);

  const t = (key) => {
    const keys = key.split(".");
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === "en" ? "nl" : "en");
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
