import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

// English translations
const en = {
  // Navigation
  nav: {
    dashboard: "Dashboard",
    observations: "Observations",
    myTasks: "My Tasks",
    causalEngine: "Causal Engine",
    actions: "Actions",
    library: "Library",
    equipmentManager: "Equipment Manager",
    settings: "Settings",
    logout: "Logout",
    userManagement: "User Management",
    statistics: "User Statistics",
    criticalityDefinitions: "Definitions",
    feedback: "Feedback",
  },
  
  // Settings pages
  settings: {
    userManagement: "User Management",
    userManagementDesc: "Manage users, roles, and permissions",
    statistics: "User Statistics",
    statisticsDesc: "View user statistics and analytics",
    criticalityDefinitions: "Definitions",
    criticalityDefinitionsDesc: "Define and customize criticality scales",
    underDevelopment: "Under Development",
    comingSoon: "This feature is coming soon. We're working hard to bring you this functionality.",
  },
  
  // Notifications
  notifications: {
    overdueActions: "Overdue Actions",
    noOverdueActions: "No overdue actions",
    viewAll: "View All",
    dueToday: "Due today",
    overdueBy1Day: "Overdue by 1 day",
    overdueByDays: "Overdue by {days} days",
  },
  
  // Definitions Page (FMEA SOD)
  definitions: {
    pageDescription: "FMEA Rating Scales for Severity, Occurrence, and Detection (SOD)",
    rpnInfo: "Risk Priority Number (RPN)",
    rpnFormula: "RPN = Severity × Occurrence × Detection. Use these tables to assign consistent ratings during FMEA analysis. The final customer should always be considered first. If both effects occur, use the higher of two Severities.",
    severity: "Severity",
    occurrence: "Occurrence",
    detection: "Detection",
    severityTitle: "Severity Evaluation Criteria",
    severityDesc: "Severity is the ranking associated with the most serious effect for a given failure mode.",
    occurrenceTitle: "Occurrence Evaluation Criteria",
    occurrenceDesc: "Occurrence is the likelihood that a specific cause/mechanism will occur, based on failure rates.",
    detectionTitle: "Detection Evaluation Criteria",
    detectionDesc: "Detection is a ranking of the ability of current controls to detect the cause/mechanism or failure mode before product reaches the customer.",
    // Criticality definitions
    criticality: "Criticality",
    criticalityTitle: "Equipment Criticality Definitions",
    criticalityDesc: "Define what each criticality level (1-5) means for your equipment hierarchy. This helps prioritize maintenance and resource allocation.",
    criticalityLevel: "Criticality Level",
    criticalityImpact: "Impact Description",
    criticalityAction: "Maintenance Strategy",
    ranking: "Rank",
    effect: "Effect",
    customerEffect: "Customer Effect (End User)",
    manufacturingEffect: "Manufacturing / Assembly Effect",
    probability: "Probability",
    description: "Description",
    failureRate: "Possible Failure Rate",
    criteria: "Criteria",
    likelihood: "Likelihood",
    detectionMethod: "Suggested Detection Method",
    // Editable definitions
    selectInstallation: "Select Installation",
    selectInstallationDesc: "Choose an installation to view or customize its definitions",
    noInstallations: "No installations found. Add installations in Equipment Manager first.",
    usingDefaults: "Using default definitions",
    usingCustom: "Using custom definitions",
    editDefinitions: "Edit Definitions",
    saveChanges: "Save Changes",
    resetToDefaults: "Reset to Defaults",
    saving: "Saving...",
    saved: "Definitions saved successfully",
    resetConfirm: "Are you sure you want to reset to default definitions? This will remove all customizations.",
    label: "Label",
    secondaryDescription: "Secondary Description",
    editRow: "Edit Row",
    viewMode: "View",
    editMode: "Edit",
  },
  
  // Dashboard
  dashboard: {
    title: "Dashboard",
    subtitle: "Overview of your risk management status",
    overallHealth: "Overall System Health",
    excellent: "Excellent",
    good: "Good",
    needsAttention: "Needs Attention",
    critical: "Critical",
    openObservations: "Open Observations",
    criticalHighRisk: "Critical/High Risk",
    overdueActions: "Overdue Actions",
    totalObservations: "Total Observations",
    totalActions: "Total Actions",
    investigations: "Investigations",
    equipment: "Equipment",
    totalAssets: "total assets",
    observationResolution: "Observation Resolution",
    actionCompletion: "Action Completion",
    investigationProgress: "Investigation Progress",
    observationsByStatus: "Observations by Status",
    observationsByRisk: "Observations by Risk Level",
    actionsByStatus: "Actions by Status",
    actionsByPriority: "Actions by Priority",
    recentObservations: "Recent Observations",
    recentActions: "Recent Actions",
    recentInvestigations: "Recent Investigations",
    noObservations: "No observations recorded",
    noActions: "No actions recorded",
    noInvestigations: "No investigations started",
    observationsByEquipment: "Observations by Equipment Type",
    operational: "Operational",
    reliabilityPerformance: "Reliability Performance",
    analytics: "Analytics",
    reliabilitySubtitle: "Holistic view of reliability management across your asset hierarchy",
    items: "items",
    dimensionDetails: "Dimension Details",
    quickStats: "Quick Stats",
    addEquipmentFirst: "Add equipment to your hierarchy to see reliability scores",
  },
  
  // Common
  common: {
    search: "Search",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    update: "Update",
    create: "Create",
    close: "Close",
    loading: "Loading...",
    noResults: "No results found",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    all: "All",
    open: "Open",
    closed: "Closed",
    inProgress: "In Progress",
    status: "Status",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    critical: "Critical",
    name: "Name",
    goBack: "Go Back",
    description: "Description",
    date: "Date",
    time: "Time",
    comment: "Comment",
    comments: "Comments",
    evidence: "Evidence",
    owner: "Owner",
    dueDate: "Due Date",
    category: "Category",
    type: "Type",
    asset: "Asset",
    location: "Location",
    equipmentType: "Equipment Type",
    failureMode: "Failure Mode",
    enterName: "Enter name",
    creating: "Creating...",
    uploading: "Uploading...",
    parsing: "Parsing...",
    assign: "Assign",
    assigning: "Assigning...",
    add: "Add",
    notLinked: "Not linked",
    discipline: "Discipline",
    optional: "Optional",
    exporting: "Exporting...",
  },
  
  // Threats page
  observations: {
    title: "Observations",
    totalObservations: "Total Observations",
    openObservations: "Open Observations",
    highPriority: "High Priority",
    searchPlaceholder: "Search threats...",
    reportThreat: "Report Observation",
    noObservations: "No threats reported",
    noObservationsDesc: "Click the + button to report your first threat",
    riskScore: "Risk Score",
    riskLevel: "Risk Level",
    rank: "Rank",
    failureMode: "Failure Mode",
    equipmentType: "Equipment Type",
    impact: "Impact",
    frequency: "Frequency",
    likelihood: "Likelihood",
    detectability: "Detectability",
    recommendedActions: "Recommended Actions",
    viewDetails: "View full details",
    startInvestigation: "Start Investigation",
    editThreat: "Edit Threat",
    deleteThreat: "Delete Threat",
    rightClickForDetails: "right-click for details",
    scoreCalculation: "Score Calculation",
    formula: "Formula",
    baseScore: "Base Score",
    criticalityMultiplier: "Criticality Multiplier",
    fmeaScores: "Likelihood Scores",
    equipmentCriticality: "Equipment Criticality",
    finalScore: "Final Score",
    noFmeaLinked: "No failure mode linked",
    noCriticalityLinked: "No criticality assigned",
    exactCalculation: "Exact Calculation",
    linkedTo: "Linked to",
    usingDefaultScore: "using default score",
    multiplier: "Multiplier",
    finalCalculation: "Final Calculation",
    riskLevelThresholds: "Risk Level Thresholds",
    linkEquipment: "Link Equipment",
    changeLink: "Change",
    linkToEquipment: "Link to Equipment",
    linkEquipmentDesc: "Select an equipment node to apply its criticality to this threat's risk score.",
    noEquipmentFound: "No equipment nodes found",
    linkAndRecalculate: "Link & Recalculate",
    linkFailureMode: "Link Failure Mode",
    linkToFailureMode: "Link to Failure Mode",
    linkFailureModeDesc: "Select a failure mode from the FMEA library to apply its severity, occurrence, and detectability scores.",
    searchFailureModes: "Search failure modes...",
    noFailureModesFound: "No failure modes found",
    relink: "Relink",
    criticalityScoreLabel: "Criticality Score",
    fmeaScoreLabel: "Likelihood Score",
    equipment: "Equipment",
    noEquipmentLinked: "No equipment linked",
    criticalityLinked: "Criticality linked",
    safety: "Safety",
    production: "Production",
    environment: "Environ.",
    reputation: "Reputation",
    location: "Location",
  },
  
  // Causal Engine
  causal: {
    title: "Causal Engine",
    investigations: "Investigations",
    newInvestigation: "New Investigation",
    overview: "Overview",
    timeline: "Timeline",
    failures: "Failures",
    causalTree: "Causal Tree",
    causes: "Causes",
    rootCauses: "Root Causes",
    events: "Events",
    sequenceOfEvents: "Sequence of Events",
    reconstructTimeline: "Reconstruct the timeline",
    addEvent: "Add Event",
    noEvents: "No events recorded",
    startAddingEvents: "Start by adding the first event",
    failureIdentification: "Failure Identification",
    defineFailure: "Define what technically failed",
    addFailure: "Add Failure",
    noFailures: "No failures identified",
    documentFailure: "Document what failed",
    buildCausalTree: "Build cause-and-effect relationships",
    addCause: "Add Cause",
    noCauses: "No causes identified",
    startBuildingTree: "Start building the causal tree",
    correctiveActions: "Corrective Actions",
    trackActions: "Track actions to prevent recurrence",
    addAction: "Add Action",
    noActions: "No actions defined",
    defineActions: "Define corrective actions",
    markAsRootCause: "Mark as Root Cause",
    parent: "Parent",
    confidence: "Confidence",
    evidenceSource: "Evidence Source",
    mechanism: "Mechanism",
    subsystem: "Subsystem",
    component: "Component",
    linkedRootCause: "Linked Root Cause",
    act: "Act",
    lead: "Lead",
    incidentDate: "Incident Date",
    draft: "Draft",
    searchInvestigations: "Search investigations...",
    noInvestigations: "No investigations yet",
    noInvestigationsDesc: "Start a new investigation to analyze equipment failures",
    editInvestigation: "Edit Investigation",
    deleteInvestigation: "Delete Investigation",
    editEvent: "Edit Event",
    editFailure: "Edit Failure",
    editCause: "Edit Cause",
    editAction: "Edit Action",
    caseNumber: "Case Number",
    openActions: "Open Actions",
    noActionsYet: "No corrective actions yet",
    defineActionsDesc: "Define actions to prevent recurrence",
    notes: "Notes",
    investigationNotes: "Investigation Notes",
    notesPlaceholder: "Add notes, observations, or important details about this investigation...",
    attachedFiles: "Attached Files",
    addFile: "Add File",
    noFilesYet: "No files attached yet",
    dropFilesHint: "Click 'Add File' to upload documents, images, or reports",
    filesUploaded: "File(s) uploaded successfully",
    uploadFailed: "Failed to upload file(s)",
    downloadFailed: "Failed to download file",
    fileDeleted: "File deleted",
    actionPromoted: "Action promoted! View it in the Actions tab.",
    actionPromoteFailed: "Failed to promote action",
    category: "Category",
    operationalEvent: "Operational Event",
    alarm: "Alarm",
    maintenanceAction: "Maintenance Action",
    humanDecision: "Human Decision",
    systemResponse: "System Response",
    environmental: "Environmental",
    selectCategory: "Select category",
    selectConfidence: "Select confidence level",
    degradationMechanism: "Degradation Mechanism",
    rootCause: "Probable Cause",
    selectParent: "Select parent cause",
    noParent: "No parent (top-level)",
    technicalCause: "Technical Cause",
    humanCause: "Human/Organizational Cause",
    externalCause: "External Cause",
    designCause: "Design/Engineering Cause",
    selectStatus: "Select status",
    selectPriority: "Select priority",
    inProgress: "In Progress",
    underReview: "Under Review",
    completed: "Completed",
    selectLinkedCause: "Select linked cause",
  },
  
  // Actions page
  actionsPage: {
    title: "Actions",
    totalActions: "Total Actions",
    pendingActions: "Pending",
    completedActions: "Completed",
    overdueActions: "Overdue",
    searchPlaceholder: "Search actions...",
    addAction: "Add Action",
    noActions: "No actions yet",
    noActionsDesc: "Actions will appear here when you promote recommendations from threats or investigations",
    source: "Source",
    assignedTo: "Assigned To",
    notStarted: "Not Started",
    completed: "Completed",
    filterByStatus: "Filter by status",
    allStatus: "All Status",
    noSourceLinked: "No source linked",
    linkedToInvestigation: "Linked to Investigation",
    linkedToThreat: "Linked to Threat",
    allDisciplines: "All Disciplines",
  },
  
  // Library page
  library: {
    title: "Library",
    failureModes: "Failure Modes",
    equipmentTypes: "Equipment Types",
    maintenance: "Maintenance",
    totalModes: "Total Modes",
    categories: "Categories",
    searchPlaceholder: "Search failure modes...",
    addFailureMode: "Add Failure Mode",
    addEquipmentType: "Add Type",
    editEquipmentType: "Edit Equipment Type",
    noFailureModes: "No failure modes found",
    noMatches: "No matches found",
    tryAdjusting: "Try adjusting your search or filters",
    linkedEquipmentTypes: "Linked Equipment Types",
    selectEquipmentTypes: "Select equipment types...",
    discipline: "Discipline",
    mechanical: "Mechanical",
    electrical: "Electrical",
    instrumentation: "Instrumentation",
    process: "Process",
    icon: "Icon",
    isoClass: "ISO Class",
    typeId: "Type ID (unique)",
    typesDefined: "types defined",
    severity: "Severity",
    occurrence: "Occurrence",
    detectability: "Detectability",
    keywords: "Keywords",
    addKeyword: "Add keyword and press Enter",
    recommendedActions: "Recommended Actions",
    addAction: "Add action and press Enter",
    allCategories: "All Categories",
    linked: "linked",
    selected: "Selected",
    types: "type(s)",
    editFailureMode: "Edit Failure Mode",
    addFailureModeDesc: "Create a new failure mode entry.",
    updateFailureModeDesc: "Update the failure mode details below.",
    category: "Category",
    equipment: "Equipment",
    equipmentPlaceholder: "e.g., Centrifugal Pump",
    failureModeName: "Failure Mode Name",
    clickToSelect: "Click to select/deselect (multiple allowed)",
    selectFailureMode: "Select a Failure Mode",
    selectFailureModeDesc: "Click on a failure mode from the list to view its details",
    riskScore: "Likelihood Score",
    linkedEquipmentTypes: "Linked Equipment Types",
    noLinkedTypes: "No equipment types linked",
    noRecommendedActions: "No recommended actions defined",
    // Validation translations
    validationStatus: "Validation Status",
    validated: "Validated",
    notValidated: "Not Yet Validated",
    notValidatedDesc: "This failure mode requires human validation",
    validate: "Validate",
    validateFailureMode: "Validate Failure Mode",
    validateFailureModeDesc: "Confirm this failure mode has been reviewed and approved by a subject matter expert",
    validatingAs: "Validating as this user",
    validatorName: "Validator Name",
    validatorNamePlaceholder: "e.g., John Smith",
    validatorPosition: "Position / Role",
    validatorPositionPlaceholder: "e.g., Reliability Engineer",
    confirmValidation: "Confirm Validation",
    validationAdded: "Validation added successfully",
    validationRemoved: "Validation removed",
    mechanism: "ISO 14224 Mechanism",
    iso14224Mechanism: "ISO 14224 Mechanism",
    pendingValidation: "Pending Validation",
    noKeywords: "No keywords",
    selectCategory: "Select category",
    // New failure mode fields
    process: "Process",
    processPlaceholder: "e.g., Extrusion, Compounding",
    potentialEffects: "Potential Effects",
    potentialEffectsPlaceholder: "e.g., Production loss, safety hazard",
    potentialCauses: "Potential Causes",
    potentialCausesPlaceholder: "e.g., Wear, contamination, incorrect settings",
    duplicateNameError: "A failure mode with this name already exists",
    exportExcel: "Export Excel",
    exportSuccess: "Failure modes exported successfully",
    exportError: "Failed to export failure modes",
  },
  
  // Equipment Manager
  equipment: {
    title: "Equipment Manager",
    hierarchy: "Hierarchy",
    tree: "Tree",
    levels: "Levels",
    properties: "Properties",
    addInstallation: "Add Installation",
    addChild: "Add Child",
    importList: "Import List",
    searchPlaceholder: "Search name, description, tag...",
    matches: "matches",
    noEquipment: "No equipment in hierarchy",
    addFirstEquipment: "Add your first installation to get started",
    selectNode: "Select a node",
    selectNodeDesc: "Click on an equipment item to view and edit its properties",
    noSelection: "No Selection",
    selectFromHierarchy: "Select an item from the hierarchy to view properties",
    dragDropTips: "Drag & Drop Tips",
    dragTip1: "Drag items to reorder within siblings",
    dragTip2: "Drop on top/bottom edge to reorder",
    dragTip3: "Drop in center to make child",
    dragToReorder: "Drag to reorder or move",
    installation: "Installation",
    plant: "Plant/Unit",
    section: "Section/System",
    equipmentUnit: "Equipment Unit",
    subunit: "Subunit",
    maintainableItem: "Maintainable Item",
    tag: "Tag",
    criticality: "Criticality",
    selectCriticality: "Select criticality...",
    safetyCritical: "Safety Critical",
    productionCritical: "Production Critical",
    noCriticality: "No criticality assigned",
    clearCriticality: "Clear criticality",
    safetyImpact: "Safety",
    productionImpact: "Production",
    environmentalImpact: "Environmental",
    reputationImpact: "Reputation",
    overallCriticality: "Overall Criticality",
    dragDropHint: "Drag items to reorder or change hierarchy",
    unassigned: "Unassigned Items",
    dragToHierarchy: "Drag to hierarchy",
    importEquipmentList: "Import Equipment List",
    pasteEquipmentList: "Paste Equipment List",
    orUpload: "or",
    uploadFile: "Upload File",
    supportedFormats: "Supported: .txt, .csv, .xlsx, .xls, .pdf",
    parseList: "Parse List",
    riskScore: "Risk Score",
    equipmentType: "Equipment Type",
    discipline: "Discipline",
    autoAssigned: "Auto-assigned from equipment type",
    selectLevel: "Select Level",
    assignToHierarchy: "Assign to Hierarchy",
    assignUnder: "Assign under",
    demoteTo: "Demote to",
    selectNewParent: "Select a new parent",
    noValidParents: "No valid parent nodes found",
    createFirst: "first",
    moving: "Moving",
    clickTarget: "Click on a green highlighted target",
    processStep: "Process Step",
    processStepPlaceholder: "e.g., Extrusion, Compounding, Mixing",
    processStepHint: "Inherited by child items",
    selectEquipment: "Select an equipment item",
    exportExcel: "Export Excel",
    exportSuccess: "Hierarchy exported successfully",
    exportError: "Failed to export hierarchy",
  },

  // Hierarchy context menu
  hierarchy: {
    addThreat: "Add Observation",
    rightClickHint: "Right-click for options",
    showDetails: "Show Details",
    equipmentType: "Equipment Type",
    discipline: "Discipline",
    criticality: "Criticality",
    notAssigned: "Not assigned",
    editInManager: "Edit in Equipment Manager",
  },
  
  // Chat
  chat: {
    title: "Report Observation",
    subtitle: "Describe the failure",
    placeholder: "Describe the issue...",
    welcomeMessage: "Hi! I'm here to help you report equipment threats. Just describe what's happening - mention the equipment and the problem, and I'll create a threat record for you.",
    threatRecorded: "Observation recorded successfully.",
    attachPhoto: "Attach photo",
    voiceInput: "Voice input",
    startCapturing: "Start Capturing Threats",
    startCapturingDesc: "Describe any equipment failure or issue. I'll analyze it and help you prioritize.",
    trySaying: "Try saying:",
    provideMoreDetails: "Please provide more details",
    voiceTranscribed: "Voice transcribed!",
    describeIssue: "Describe the failure or issue...",
    newFailureMode: "New Failure Mode",
    specifyFailureMode: "Specify the failure mode name:",
    enterFailureModeName: "Enter failure mode name...",
  },
  
  // Info dialog
  info: {
    title: "AssetIQ - Risk Methodology",
    fmeaScoring: "Likelihood Scoring",
    fmeaDescription: "Likelihood Score is calculated using Failure Mode and Effects Analysis methodology:",
    formula: "Likelihood Score = (Severity × Occurrence × Detection) / 10",
    maxScore: "Maximum score: 100",
    severity: "Severity (Repair Complexity)",
    severityScale: "1-3: Quickly fixable | 4-6: Normal fix | 7-9: Complex fix | 10: Full replacement",
    severity1to3: "1-3: Quickly fixable",
    severity4to6: "4-6: Normal fix",
    severity7to9: "7-9: Complex fix",
    severity10: "10: Full replacement",
    occurrence: "Occurrence (Expected Interval)",
    occurrenceScale: "1-3: 10-20 years | 4-6: 1-10 years | 7-9: 1-6 months | 10: Weeks",
    occurrence1to3: "1-3: Every 10-20 years",
    occurrence4to6: "4-6: Every 1-10 years",
    occurrence7to9: "7-9: Every 1-6 months",
    occurrence10: "10: Every few weeks",
    detection: "Detection (Difficulty)",
    detectionScale: "1-3: Easy to detect | 4-6: Moderate | 7-9: Difficult | 10: Undetectable",
    detection1to3: "1-3: Easy to detect",
    detection4to6: "4-6: Moderate",
    detection7to9: "7-9: Difficult",
    detection10: "10: Undetectable",
    riskLevels: "Risk Levels",
    criticalityDimensions: "4-Dimension Criticality Assessment",
    criticalityDimensionsDesc: "Criticality Score is calculated from 4 weighted dimensions, each rated 1-5:",
    safetyDimension: "Safety Impact",
    productionDimension: "Production Impact",
    environmentalDimension: "Environmental Impact",
    reputationDimension: "Reputation Impact",
    weight: "Weight",
    criticalityFormula: "Criticality Score = (Safety×25 + Production×20 + Environmental×15 + Reputation×10) / 3.5",
    overallCriticalityDesc: "Maximum Criticality Score: 100",
    finalRiskFormula: "Final Risk Score",
    finalRiskFormulaDesc: "The final risk score uses weighted components:",
    finalRiskFormulaCalc: "Risk Score = (Criticality × 0.75) + (Likelihood × 0.25)",
    quickTips: "Quick Tips",
    tip1: "Use the + button to report new threats via chat",
    tip2: "Drag and drop equipment in the hierarchy to reorganize",
    tip3: "Click on a threat to view details and start investigations",
    tip4: "Use the Causal Engine to perform root cause analysis",
    tip5: "Promote recommendations to Actions for tracking",
  },
  
  // Auth
  auth: {
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    name: "Name",
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your account",
    registerTitle: "Create account",
    registerSubtitle: "Start managing equipment threats",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    signUp: "Sign up",
    signIn: "Sign in",
    forgotPassword: "Forgot password?",
    forgotPasswordSubtitle: "Enter your email and we'll send you a link to reset your password.",
    resetPassword: "Reset Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    resetLinkSent: "Reset link sent! Check your email.",
    passwordResetSuccess: "Password has been reset successfully.",
  },

  // AI Features
  ai: {
    riskAnalysis: "AI Risk Analysis",
    causalIntelligence: "Causal Intelligence",
    analyzeWithAi: "Analyze with AI",
    analyzing: "Analyzing...",
    whyIsThisHappening: "Why is this happening?",
    analyzingCauses: "Analyzing causes...",
    riskScore: "Risk Score",
    failureProbability: "Failure Probability",
    timeToFailure: "Time to Failure",
    trendChange: "Trend Change",
    keyRiskFactors: "Key Risk Factors",
    riskForecast: "Risk Forecast",
    keyInsights: "Key Insights",
    aiRecommendations: "AI Recommendations",
    lastAnalyzed: "Last analyzed",
    probableCauses: "Probable Causes",
    rankedByLikelihood: "ranked by likelihood",
    supportingEvidence: "Supporting Evidence",
    recommendedMitigations: "Recommended Mitigations",
    contributingFactors: "Contributing Factors",
    analysisConfidence: "Analysis confidence",
    startInvestigationWithAi: "Start Investigation with AI Insights",
    creatingInvestigation: "Creating Investigation...",
    addAsAction: "Add as action",
    addedAsAction: "Added as action",
    actionCreated: "Action created from AI recommendation!",
    addToThreat: "Add to threat recommendations",
    alreadyAdded: "Already added",
    recommendationAdded: "Recommendation added to threat!",
    recommendationExists: "Recommendation already exists",
    recommendationFailed: "Failed to add recommendation",
    investigationCreated: "Investigation created with AI insights!",
    increasing: "Increasing",
    stable: "Stable",
    decreasing: "Decreasing",
    highConfidence: "High confidence",
    mediumConfidence: "Medium confidence",
    lowConfidence: "Low confidence",
    veryLikely: "Very Likely",
    likely: "Likely",
    possible: "Possible",
    unlikely: "Unlikely",
    technicalCause: "Technical",
    humanFactor: "Human Factor",
    maintenanceIssue: "Maintenance",
    designIssue: "Design Issue",
    organizationalFactor: "Organizational",
    externalCondition: "External",
    causesIdentified: "probable causes identified",
    unknown: "Unknown",
    missingLibraryData: "Missing Library Data",
    missingLibraryDataDesc: "The following items are not in your library. Add them for better AI analysis accuracy:",
    goToLibrary: "Go to Library",
  },

  // Threat Detail
  threatDetail: {
    title: "Threat Details",
    backToThreats: "Back to Threats",
    riskScoreCard: "Risk Score",
    threatInfo: "Threat Information",
    equipmentInfo: "Equipment Information",
    causeAnalysis: "Cause Analysis",
    recommendedActions: "Recommended Actions",
    addAction: "Add Action",
    createAction: "Create Action",
    actionTitle: "Title",
    actionDescription: "Description",
    actionPriority: "Priority",
    actionAssignee: "Assignee",
    actionDueDate: "Due Date",
    deleteConfirm: "Are you sure?",
    deleteWarning: "This will permanently delete this threat and all associated data.",
    mitigated: "Mitigated",
    createdAt: "Created",
  },

  // Maintenance Strategies
  maintenance: {
    title: "Maintenance Strategies",
    subtitle: "AI-generated maintenance plans by equipment type",
    generateStrategy: "Generate Strategy",
    generateAll: "Generate All",
    generating: "Generating...",
    noStrategies: "No maintenance strategies yet",
    noStrategiesDesc: "Generate maintenance strategies for your equipment types",
    selectEquipmentType: "Select Equipment Type",
    operatorRounds: "Operator Rounds",
    detectionSystems: "Detection Systems",
    scheduledMaintenance: "Scheduled Maintenance",
    correctiveActions: "Corrective Actions",
    emergencyProcedures: "Emergency Procedures",
    spareParts: "Spare Parts",
    safetyCritical: "Safety Critical",
    productionCritical: "Production Critical",
    frequency: "Frequency",
    discipline: "Discipline",
    resources: "Resources",
    duration: "Duration",
    detects: "Detects",
    prevents: "Prevents",
    addresses: "Addresses",
    checksFor: "Checks for",
    sensor: "sensor",
    sensors: "sensors",
    task: "execution",
    tasks: "executions",
    action: "action",
    round: "round",
    rounds: "rounds",
    procedure: "procedure",
    procedures: "procedures",
    part: "part",
    parts: "parts",
    deleteStrategy: "Delete Strategy?",
    deleteStrategyDesc: "This will permanently delete the maintenance strategy for",
    allCriticalityLevels: "all criticality levels",
    autoGenerated: "Auto-generated from FMEA",
    criticalityLevels: "criticality levels",
    editItem: "Edit Item",
    addItem: "Add Item",
    itemName: "Item Name",
    checklistItems: "Checklist Items",
    failureModesAddressed: "Failure Modes Addressed",
    failureModesDetected: "Failure Modes Detected",
    sensorType: "Sensor Type",
    alertThreshold: "Alert Threshold",
    alarmThreshold: "Alarm Threshold",
    tripThreshold: "Trip Threshold",
    partNumber: "Part Number",
    quantity: "Quantity",
    minStock: "Min Stock",
    leadTime: "Lead Time",
    estimatedCost: "Estimated Cost",
    triggerConditions: "Trigger Conditions",
    immediateActions: "Immediate Actions",
    notificationList: "Notification List",
  },

  // Reliability Performance
  reliability: {
    title: "Reliability Performance",
    subtitle: "Holistic view of reliability management across your asset hierarchy",
    overallScore: "Overall Score",
    equipmentHealth: "Equipment Health",
    dimensionBreakdown: "Dimension Breakdown",
    criticalityDimension: "Criticality",
    incidentsDimension: "Incidents",
    investigationsDimension: "Investigations",
    maintenanceDimension: "Maintenance",
    reactionsDimension: "Reactions",
    threatsDimension: "Observations",
    withCriticality: "With Criticality",
    openObservations: "Open Observations",
    totalInvestigations: "Investigations",
    totalActions: "Total Actions",
    filterByLevel: "Filter by Level",
    allLevels: "All Levels",
    searchEquipment: "Search equipment...",
    noEquipment: "No equipment found",
    addEquipmentToSee: "Add equipment to your hierarchy to see reliability scores",
    frameworkInfo: "Framework Methodology",
    frameworkDescription: "The reliability performance score is calculated across 6 dimensions:",
    criticalityDesc: "Equipment hierarchy completeness and criticality assignments",
    incidentsDesc: "Incident records and positive validation",
    investigationsDesc: "Cross-asset analysis coverage",
    maintenanceDesc: "Active maintenance plans and spares",
    reactionsDesc: "Clear reaction plans (resources, support, downtime)",
    threatsDesc: "Unmitigated threat management",
    good: "Good",
    fair: "Fair",
    poor: "Poor",
    crit: "Crit",
    maint: "Maint",
  },

  // Task Scheduler
  taskScheduler: {
    title: "Task Planner",
    subtitle: "Manage task templates, plans, and schedules",
    generateExecutions: "Generate Schedule",
    newTemplate: "Design Task",
    totalExecutions: "Total Executions",
    planned: "Planned",
    overdue: "Overdue",
    executions: "Schedule",
    plans: "Plans",
    templates: "Task Designs",
    allStatus: "All Status",
    searchTemplates: "Search task designs...",
    allDisciplines: "All Disciplines",
    operations: "Operations",
    maintenance: "Maintenance",
    laboratory: "Laboratory",
    inspection: "Inspection",
    engineering: "Engineering",
    noExecutionsFound: "No executions found",
    generateFromPlans: "Generate from plans",
    execution: "Task Planner",
    equipment: "Equipment",
    scheduled: "Scheduled",
    start: "Start",
    complete: "Complete",
    newPlan: "New Plan",
    noPlansYet: "No execution plans created yet",
    createPlansDesc: "Create plans from task designs to schedule recurring executions",
    createFirstPlan: "Create First Plan",
    active: "Active",
    inactive: "Inactive",
    deletePlan: "Delete Plan",
    every: "Every",
    next: "Next",
    linkedForm: "Linked Form",
    selectForm: "Select a form",
    noTemplatesFound: "No task designs found",
    createFirstTemplate: "Create your first template",
    noDescription: "No description",
    usedInPlans: "Used in",
    editTemplate: "Edit Task Design",
    createTemplate: "Create Task Design",
    strategy: "Strategy",
    preventive: "Preventive",
    predictive: "Predictive",
    detective: "Detective",
    corrective: "Corrective",
    defaultInterval: "Default Interval",
    days: "Days",
    weeks: "Weeks",
    months: "Months",
    durationMin: "Duration (min)",
    saving: "Saving...",
    saveChanges: "Save Changes",
    completeExecution: "Complete Execution",
    completing: "Completing",
    completionNotes: "Completion Notes",
    anyObservations: "Any observations or notes...",
    needsFollowUp: "Needs follow-up action",
    markComplete: "Mark Complete",
    deleteExecution: "Delete Execution",
    deleteExecutionConfirm: "Are you sure you want to delete this execution? This action cannot be undone.",
    deleting: "Deleting...",
    createPlan: "Create Execution Plan",
    createPlanDesc: "Schedule recurring executions for equipment",
    executionTemplate: "Task Design",
    selectTemplate: "Select a task design",
    selectEquipment: "Select equipment",
    interval: "Interval",
    inheritedFromTemplate: "Inherited from template",
    reset: "Reset",
    templateDefault: "Task design default",
    beginDate: "Begin Date",
    selectDate: "Select date",
    today: "Today",
    clear: "Clear",
    whenToStart: "When to start scheduling",
    endDateOptional: "End Date (Optional)",
    whenToStop: "When to stop scheduling",
    linkedFormOptional: "Linked Form (Optional)",
    selectFormTemplate: "Select a form template",
    noForm: "No form",
    linkFormDesc: "Link a form to be filled during execution",
    optionalNotes: "Optional notes about this plan",
    // Ad-hoc execution
    executeNow: "Execute Now",
    executeAdhocTitle: "Create Ad-hoc Execution",
    executeAdhocDesc: "Create a one-time task execution from this task design without a recurring schedule",
    selectedTemplate: "Selected Template",
    noEquipment: "No specific equipment",
    priority: "Priority",
    notes: "Notes",
    adhocNotesPlaceholder: "Optional notes about this ad-hoc execution...",
    createAdhocTask: "Create Execution",
    adhocTaskCreated: "Ad-hoc execution created successfully",
    template: "Template",
    // Ad-hoc template creation
    adhocOnly: "Ad-hoc Only",
    adhocOnlyDesc: "No recurring schedule - execute manually when needed",
    adhocLabel: "Ad-hoc",
    adhocTemplateHint: "Ad-hoc task",
    adhocPlanDesc: "This is an ad-hoc template - no recurring schedule needed",
    intervalOptional: "Interval (Optional for ad-hoc)",
    editPlan: "Edit Execution Plan",
    editPlanDesc: "Modify plan settings and scheduling",
    planStatus: "Plan Status",
    planStatusDesc: "Enable or disable this plan",
  },

  // Forms
  forms: {
    title: "Form Designer",
    subtitle: "Create and manage data collection forms",
    templates: "Templates",
    submissions: "Submissions",
    warnings: "Warnings",
    critical: "Critical",
    operations: "Operations",
    maintenance: "Maintenance",
    inspection: "Inspection",
    lab: "Lab",
    noTemplatesYet: "No form templates yet",
    noTemplatesDesc: "Create your first form template to start collecting data",
    noSubmissionsYet: "No submissions yet",
    noSubmissionsDesc: "Submissions will appear here when forms are filled",
    templateName: "Name",
    templateDescription: "Description",
    discipline: "Discipline",
    requireSignature: "Require Signature",
    allowPartialSubmit: "Allow Partial Submit",
    formFields: "Form Fields",
    noFieldsYet: "No fields added yet",
    addFieldHint: "Click \"Add Field\" to start building your form",
    label: "Label",
    fieldType: "Field Type",
    notes: "Notes",
    // Documents
    documents: "Documents",
    referenceDocuments: "Reference Documents",
    referenceDocumentsHint: "Add manuals, SOPs, or guides that can be searched with AI during execution",
    addDocument: "Add Document",
    pendingUpload: "Pending upload",
    noDocuments: "No documents attached",
    noDocumentsHint: "Upload PDFs, manuals, or reference materials",
    attachedDocuments: "Attached Documents",
    noDocumentsAttached: "No documents attached to this form",
    aiDocumentSearch: "AI Document Search",
    searchDocumentsPlaceholder: "Ask a question about the attached documents...",
    askAI: "Ask AI",
    documentUploaded: "Document uploaded successfully",
  },

  // Decision Engine
  decisionEngine: {
    title: "Decision Engine",
    subtitle: "Automated learning rules & suggestions",
    pending: "Pending",
    approved: "Approved",
    executed: "Executed",
    highPriority: "High Priority",
    rulesActive: "Rules Active",
    allStatus: "All Status",
    allPriority: "All Priority",
    noSuggestionsYet: "No suggestions yet",
    noSuggestionsDesc: "Click \"Evaluate Rules\" to generate suggestions based on your data",
    noRulesConfigured: "No rules configured",
    noRulesDesc: "Rules will appear here once initialized",
    enabled: "Enabled",
    enabledDesc: "Rule will generate suggestions when enabled",
    autoExecute: "Auto-Execute",
    autoExecuteDesc: "Execute suggestions automatically without approval",
    configuration: "Configuration",
    notesOptional: "Notes (optional)",
    reasonOptional: "Reason (optional)",
    recommendedAction: "Recommended Action",
    autoExecuteNote: "This rule executes automatically",
    rejectionReason: "Rejection reason",
    rejected: "Rejected",
  },

  // Analytics Dashboard
  analyticsDashboard: {
    title: "Analytics Dashboard",
    subtitle: "Real-time reliability intelligence",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
    last90Days: "Last 90 days",
    topRisksByRPN: "Top Risks by RPN",
    topRisksDesc: "Equipment Failure Modes with highest risk",
    noRiskData: "No risk data available",
    failureModePareto: "Failure Mode Pareto",
    failureModeParetoDesc: "Most observed failure modes",
    noObservationData: "No observation data",
    equipmentRiskRanking: "Equipment Risk Ranking",
    equipmentRiskDesc: "Equipment by aggregated failure mode risk",
    noEquipmentData: "No equipment data",
    detectionEffectiveness: "Detection Effectiveness",
    detectionEffectivenessDesc: "Task templates by issue detection rate",
    noDataYet: "No data yet",
    noConcerns: "No concerns",
    taskWorkload: "Task Workload",
    taskWorkloadDesc: "Upcoming 7-day task distribution",
    noScheduledTasks: "No scheduled tasks",
  },

  // User Management
  userManagement: {
    title: "User Management",
    subtitle: "Manage user roles and permissions",
    allRoles: "All Roles",
    noUsersFound: "No users found",
    user: "User",
    role: "Role",
    department: "Department",
    lastLogin: "Last Login",
    editUserProfile: "Edit User Profile",
    phone: "Phone",
    position: "Position",
    changeUserRole: "Change User Role",
    score: "SCORE",
    // Photo upload
    uploadPhoto: "Upload Photo",
    changePhoto: "Change Photo",
    removePhoto: "Remove Photo",
    photoUploading: "Uploading...",
    photoUploaded: "Photo uploaded successfully",
    photoRemoved: "Photo removed",
    photoError: "Failed to upload photo",
    invalidFileType: "Invalid file type. Please use JPEG, PNG, GIF, or WebP.",
    fileTooLarge: "File too large. Maximum size is 5MB.",
    // Image Editor
    editPhoto: "Edit Photo",
    zoom: "Zoom",
    brightness: "Brightness",
    contrast: "Contrast",
    rotateLeft: "Rotate Left",
    rotateRight: "Rotate Right",
    flipHorizontal: "Flip Horizontal",
    flipVertical: "Flip Vertical",
    reset: "Reset",
    savePhoto: "Save Photo",
    saving: "Saving...",
  },

  // User Statistics
  userStatistics: {
    title: "User Statistics",
    subtitle: "System usage and engagement overview",
    activeUsers: "Active Users",
    totalSessions: "Total Sessions",
    totalViews: "Total Views",
    avgSessionDuration: "Avg. Duration",
    mostUsedModule: "Most Used",
    leastUsedModule: "Least Used",
    moduleUsage: "Module Usage",
    usageDistribution: "Usage Distribution",
    dailyActiveUsers: "Daily Active Users",
    dailyViews: "Daily Views",
    userActivity: "User Activity",
    featureUsage: "Feature Usage",
    overview: "Overview",
    modules: "Modules",
    users: "Users",
    actions: "Actions",
    noDataAvailable: "No data available",
    accessRestricted: "Access Restricted",
    accessDeniedMessage: "You do not have permission to view user statistics.",
    allRoles: "All Roles",
    allActivity: "All Activity",
    active: "Active",
    lowActivity: "Low Activity",
    inactive: "Inactive",
    lastActive: "Last Active",
    sessions: "Sessions",
    mostUsed: "Most Used",
    totalCount: "Total Count",
    uniqueUsers: "Unique Users",
    percentOfTotal: "% of Total",
    avgTimeSpent: "Avg. Time (s)",
    today: "Today",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
  },

  // Feedback
  feedback: {
    title: "Feedback",
    subtitle: "Your submissions",
    noFeedbackYet: "No feedback yet",
    noFeedbackDesc: "Share your thoughts, report issues, or suggest improvements.",
    sendFeedback: "Send feedback",
    newFeedback: "Send Feedback",
    newFeedbackDesc: "Share your thoughts, report an issue, or suggest an improvement.",
    editFeedback: "Edit Feedback",
    editFeedbackDesc: "Update your feedback details.",
    type: "Type",
    typeIssue: "Issue",
    typeImprovement: "Improvement",
    typeGeneral: "General",
    severity: "Severity",
    selectSeverity: "Select severity",
    message: "Message",
    messagePlaceholder: "Describe your feedback...",
    messageRequired: "Please enter a message",
    screenshot: "Screenshot",
    attachScreenshot: "Attach screenshot",
    submit: "Submit",
    submitted: "Feedback submitted successfully",
    updated: "Feedback updated successfully",
    deleted: "Feedback deleted",
    statusUpdated: "Status updated",
    deleteConfirm: "Delete Feedback?",
    deleteConfirmDesc: "This action cannot be undone. This will permanently delete your feedback.",
    submittedBy: "Submitted by",
    response: "Response",
    statusNew: "New",
    statusInReview: "In Review",
    statusResolved: "Resolved",
    statusPlanned: "Planned",
    statusWontFix: "Won't Fix",
  },
};

// Dutch translations
const nl = {
  // Navigation
  nav: {
    dashboard: "Dashboard",
    observations: "Observaties",
    myTasks: "Mijn Taken",
    causalEngine: "Oorzaakanalyse",
    actions: "Acties",
    library: "Bibliotheek",
    equipmentManager: "Apparatuurbeheer",
    settings: "Instellingen",
    logout: "Uitloggen",
    userManagement: "Gebruikersbeheer",
    statistics: "Gebruikersstatistieken",
    criticalityDefinitions: "Definities",
    feedback: "Feedback",
  },
  
  // Settings pages
  settings: {
    userManagement: "Gebruikersbeheer",
    userManagementDesc: "Beheer gebruikers, rollen en rechten",
    statistics: "Gebruikersstatistieken",
    statisticsDesc: "Bekijk gebruikersstatistieken en analyses",
    criticalityDefinitions: "Definities",
    criticalityDefinitionsDesc: "Definieer en pas kriticiteitsschalen aan",
    underDevelopment: "In ontwikkeling",
    comingSoon: "Deze functie komt binnenkort. We werken hard om u deze functionaliteit te bieden.",
  },
  
  // Notifications
  notifications: {
    overdueActions: "Achterstallige Acties",
    noOverdueActions: "Geen achterstallige acties",
    viewAll: "Alles bekijken",
    dueToday: "Vandaag verschuldigd",
    overdueBy1Day: "1 dag achterstallig",
    overdueByDays: "{days} dagen achterstallig",
  },
  
  // Definitions Page (FMEA SOD)
  definitions: {
    pageDescription: "FMEA Beoordelingsschalen voor Ernst, Frequentie en Detectie (SOD)",
    rpnInfo: "Risico Prioriteitsnummer (RPN)",
    rpnFormula: "RPN = Ernst × Frequentie × Detectie. Gebruik deze tabellen om consistente beoordelingen toe te kennen tijdens FMEA-analyse. De eindklant moet altijd eerst worden overwogen. Als beide effecten optreden, gebruik de hogere van twee Ernstniveaus.",
    severity: "Ernst",
    occurrence: "Frequentie",
    detection: "Detectie",
    severityTitle: "Ernst Evaluatiecriteria",
    severityDesc: "Ernst is de rangschikking gekoppeld aan het meest ernstige effect voor een bepaalde faalwijze.",
    occurrenceTitle: "Frequentie Evaluatiecriteria",
    occurrenceDesc: "Frequentie is de waarschijnlijkheid dat een specifieke oorzaak/mechanisme zal optreden, gebaseerd op faalpercentages.",
    detectionTitle: "Detectie Evaluatiecriteria",
    detectionDesc: "Detectie is een rangschikking van het vermogen van huidige controles om de oorzaak/mechanisme of faalwijze te detecteren voordat het product de klant bereikt.",
    // Kritikaliteitsdefinities
    criticality: "Kritikaliteit",
    criticalityTitle: "Apparatuur Kritikaliteitsdefinities",
    criticalityDesc: "Definieer wat elk kritikaliteitsniveau (1-5) betekent voor uw apparatuurhiërarchie. Dit helpt bij het prioriteren van onderhoud en middelentoewijzing.",
    criticalityLevel: "Kritikaliteitsniveau",
    criticalityImpact: "Impactbeschrijving",
    criticalityAction: "Onderhoudsstrategie",
    ranking: "Rang",
    effect: "Effect",
    customerEffect: "Klanteffect (Eindgebruiker)",
    manufacturingEffect: "Productie / Assemblage Effect",
    probability: "Waarschijnlijkheid",
    description: "Beschrijving",
    failureRate: "Mogelijke Faalpercentage",
    criteria: "Criteria",
    likelihood: "Waarschijnlijkheid",
    detectionMethod: "Voorgestelde Detectiemethode",
    // Bewerkbare definities
    selectInstallation: "Selecteer Installatie",
    selectInstallationDesc: "Kies een installatie om de definities te bekijken of aan te passen",
    noInstallations: "Geen installaties gevonden. Voeg eerst installaties toe in Equipment Manager.",
    usingDefaults: "Standaard definities gebruiken",
    usingCustom: "Aangepaste definities gebruiken",
    editDefinitions: "Definities Bewerken",
    saveChanges: "Wijzigingen Opslaan",
    resetToDefaults: "Terugzetten naar Standaard",
    saving: "Opslaan...",
    saved: "Definities succesvol opgeslagen",
    resetConfirm: "Weet u zeker dat u wilt terugzetten naar standaard definities? Dit verwijdert alle aanpassingen.",
    label: "Label",
    secondaryDescription: "Secundaire Beschrijving",
    editRow: "Rij Bewerken",
    viewMode: "Bekijken",
    editMode: "Bewerken",
  },
  
  // Dashboard
  dashboard: {
    title: "Dashboard",
    subtitle: "Overzicht van uw risicobeheer status",
    overallHealth: "Algemene Systeemgezondheid",
    excellent: "Uitstekend",
    good: "Goed",
    needsAttention: "Aandacht nodig",
    critical: "Kritiek",
    openObservations: "Open dreigingen",
    criticalHighRisk: "Kritiek/Hoog risico",
    overdueActions: "Achterstallige acties",
    totalObservations: "Totaal dreigingen",
    totalActions: "Totaal acties",
    investigations: "Onderzoeken",
    equipment: "Apparatuur",
    totalAssets: "totale assets",
    observationResolution: "Dreigingsoplossing",
    actionCompletion: "Actie-afronding",
    investigationProgress: "Onderzoeksvoortgang",
    observationsByStatus: "Dreigingen per status",
    observationsByRisk: "Dreigingen per risiconiveau",
    actionsByStatus: "Acties per status",
    actionsByPriority: "Acties per prioriteit",
    recentObservations: "Recente dreigingen",
    recentActions: "Recente acties",
    recentInvestigations: "Recente onderzoeken",
    noObservations: "Geen dreigingen geregistreerd",
    noActions: "Geen acties geregistreerd",
    noInvestigations: "Geen onderzoeken gestart",
    observationsByEquipment: "Dreigingen per apparaattype",
    operational: "Operationeel",
    reliabilityPerformance: "Betrouwbaarheidsprestaties",
    analytics: "Analyse",
    reliabilitySubtitle: "Holistisch overzicht van betrouwbaarheidsbeheer over uw assethiërarchie",
    items: "items",
    dimensionDetails: "Dimensie details",
    quickStats: "Snelle statistieken",
    addEquipmentFirst: "Voeg apparatuur toe aan uw hiërarchie om betrouwbaarheidsscores te zien",
  },
  
  // Common
  common: {
    search: "Zoeken",
    add: "Toevoegen",
    edit: "Bewerken",
    delete: "Verwijderen",
    cancel: "Annuleren",
    save: "Opslaan",
    update: "Bijwerken",
    create: "Aanmaken",
    close: "Sluiten",
    loading: "Laden...",
    noResults: "Geen resultaten gevonden",
    confirm: "Bevestigen",
    yes: "Ja",
    no: "Nee",
    all: "Alle",
    open: "Open",
    closed: "Gesloten",
    inProgress: "In uitvoering",
    status: "Status",
    priority: "Prioriteit",
    high: "Hoog",
    medium: "Gemiddeld",
    low: "Laag",
    critical: "Kritiek",
    name: "Naam",
    goBack: "Terug",
    description: "Beschrijving",
    date: "Datum",
    time: "Tijd",
    comment: "Opmerking",
    comments: "Opmerkingen",
    evidence: "Bewijs",
    owner: "Eigenaar",
    dueDate: "Vervaldatum",
    category: "Categorie",
    type: "Type",
    asset: "Asset",
    location: "Locatie",
    equipmentType: "Apparatuurtype",
    failureMode: "Faalmodus",
    enterName: "Voer naam in",
    creating: "Aanmaken...",
    uploading: "Uploaden...",
    parsing: "Verwerken...",
    assign: "Toewijzen",
    assigning: "Toewijzen...",
    add: "Toevoegen",
    notLinked: "Niet gekoppeld",
    discipline: "Discipline",
    optional: "Optioneel",
    exporting: "Exporteren...",
  },
  
  // Threats page
  observations: {
    title: "Dreigingen",
    totalObservations: "Totaal dreigingen",
    openObservations: "Open dreigingen",
    highPriority: "Hoge prioriteit",
    searchPlaceholder: "Zoek dreigingen...",
    reportThreat: "Dreiging melden",
    noObservations: "Geen dreigingen gemeld",
    noObservationsDesc: "Klik op de + knop om uw eerste dreiging te melden",
    riskScore: "Risicoscore",
    riskLevel: "Risiconiveau",
    rank: "Rang",
    failureMode: "Faalmodus",
    equipmentType: "Apparatuurtype",
    impact: "Impact",
    frequency: "Frequentie",
    likelihood: "Waarschijnlijkheid",
    detectability: "Detecteerbaarheid",
    recommendedActions: "Aanbevolen acties",
    viewDetails: "Bekijk details",
    startInvestigation: "Start onderzoek",
    editThreat: "Bewerk dreiging",
    deleteThreat: "Verwijder dreiging",
    rightClickForDetails: "rechtsklik voor details",
    scoreCalculation: "Score Berekening",
    formula: "Formule",
    baseScore: "Basisscore",
    criticalityMultiplier: "Kriticiteits Vermenigvuldiger",
    fmeaScores: "Likelihood Scores",
    equipmentCriticality: "Apparatuur Kriticiteit",
    finalScore: "Eindscore",
    noFmeaLinked: "Geen faalmodus gekoppeld",
    noCriticalityLinked: "Geen kriticiteit toegewezen",
    exactCalculation: "Exacte Berekening",
    linkedTo: "Gekoppeld aan",
    usingDefaultScore: "standaard score gebruikt",
    multiplier: "Vermenigvuldiger",
    finalCalculation: "Eindberekening",
    riskLevelThresholds: "Risiconiveau Drempels",
    linkEquipment: "Koppel Apparatuur",
    changeLink: "Wijzig",
    linkToEquipment: "Koppelen aan Apparatuur",
    linkEquipmentDesc: "Selecteer een apparatuur om de kriticiteit toe te passen op de risicoscore van deze dreiging.",
    noEquipmentFound: "Geen apparatuur gevonden",
    linkAndRecalculate: "Koppel & Herbereken",
    linkFailureMode: "Koppel Faalmodus",
    linkToFailureMode: "Koppelen aan Faalmodus",
    linkFailureModeDesc: "Selecteer een faalmodus uit de FMEA bibliotheek om de ernst, frequentie en detecteerbaarheidsscores toe te passen.",
    searchFailureModes: "Zoek faalmodi...",
    noFailureModesFound: "Geen faalmodi gevonden",
    relink: "Herkoppelen",
    criticalityScoreLabel: "Kriticiteits Score",
    fmeaScoreLabel: "Likelihood Score",
    equipment: "Apparatuur",
    noEquipmentLinked: "Geen apparatuur gekoppeld",
    criticalityLinked: "Kriticiteit gekoppeld",
    safety: "Veiligheid",
    production: "Productie",
    environment: "Milieu",
    reputation: "Reputatie",
    location: "Locatie",
  },
  
  // Causal Engine
  causal: {
    title: "Oorzaakanalyse",
    investigations: "Onderzoeken",
    newInvestigation: "Nieuw onderzoek",
    overview: "Overzicht",
    timeline: "Tijdlijn",
    failures: "Falen",
    causalTree: "Oorzakenboom",
    causes: "Oorzaken",
    rootCauses: "Grondoorzaken",
    events: "Gebeurtenissen",
    sequenceOfEvents: "Volgorde van gebeurtenissen",
    reconstructTimeline: "Reconstrueer de tijdlijn",
    addEvent: "Gebeurtenis toevoegen",
    noEvents: "Geen gebeurtenissen vastgelegd",
    startAddingEvents: "Begin met het toevoegen van de eerste gebeurtenis",
    failureIdentification: "Faalidentificatie",
    defineFailure: "Definieer wat technisch gefaald heeft",
    addFailure: "Falen toevoegen",
    noFailures: "Geen falen geïdentificeerd",
    documentFailure: "Documenteer wat gefaald heeft",
    buildCausalTree: "Bouw oorzaak-en-gevolg relaties",
    addCause: "Oorzaak toevoegen",
    noCauses: "Geen oorzaken geïdentificeerd",
    startBuildingTree: "Begin met het bouwen van de oorzakenboom",
    correctiveActions: "Corrigerende acties",
    trackActions: "Volg acties om herhaling te voorkomen",
    addAction: "Actie toevoegen",
    noActions: "Geen acties gedefinieerd",
    defineActions: "Definieer corrigerende acties",
    markAsRootCause: "Markeer als grondoorzaak",
    parent: "Ouder",
    confidence: "Vertrouwen",
    evidenceSource: "Bewijsbron",
    mechanism: "Mechanisme",
    subsystem: "Subsysteem",
    component: "Component",
    linkedRootCause: "Gekoppelde grondoorzaak",
    act: "Actie",
    lead: "Leider",
    incidentDate: "Incidentdatum",
    draft: "Concept",
    searchInvestigations: "Zoek onderzoeken...",
    noInvestigations: "Nog geen onderzoeken",
    noInvestigationsDesc: "Start een nieuw onderzoek om apparatuurstoringen te analyseren",
    editInvestigation: "Onderzoek bewerken",
    deleteInvestigation: "Onderzoek verwijderen",
    editEvent: "Gebeurtenis bewerken",
    editFailure: "Falen bewerken",
    editCause: "Oorzaak bewerken",
    editAction: "Actie bewerken",
    caseNumber: "Zaaknummer",
    openActions: "Open acties",
    noActionsYet: "Nog geen corrigerende acties",
    defineActionsDesc: "Definieer acties om herhaling te voorkomen",
    notes: "Notities",
    investigationNotes: "Onderzoeksnotities",
    notesPlaceholder: "Voeg notities, observaties of belangrijke details over dit onderzoek toe...",
    attachedFiles: "Bijgevoegde bestanden",
    addFile: "Bestand toevoegen",
    noFilesYet: "Nog geen bestanden bijgevoegd",
    dropFilesHint: "Klik op 'Bestand toevoegen' om documenten, afbeeldingen of rapporten te uploaden",
    filesUploaded: "Bestand(en) succesvol geüpload",
    uploadFailed: "Uploaden van bestand(en) mislukt",
    downloadFailed: "Downloaden van bestand mislukt",
    fileDeleted: "Bestand verwijderd",
    actionPromoted: "Actie gepromoveerd! Bekijk het in het Acties tabblad.",
    actionPromoteFailed: "Actie promoveren mislukt",
    category: "Categorie",
    operationalEvent: "Operationele gebeurtenis",
    alarm: "Alarm",
    maintenanceAction: "Onderhoudsactie",
    humanDecision: "Menselijke beslissing",
    systemResponse: "Systeemreactie",
    environmental: "Omgevingsfactor",
    selectCategory: "Selecteer categorie",
    selectConfidence: "Selecteer betrouwbaarheidsniveau",
    degradationMechanism: "Degradatiemechanisme",
    rootCause: "Waarschijnlijke Oorzaak",
    selectParent: "Selecteer bovenliggende oorzaak",
    noParent: "Geen ouder (top-niveau)",
    technicalCause: "Technische oorzaak",
    humanCause: "Menselijke/Organisatorische oorzaak",
    externalCause: "Externe oorzaak",
    designCause: "Ontwerp/Engineering oorzaak",
    selectStatus: "Selecteer status",
    selectPriority: "Selecteer prioriteit",
    inProgress: "In uitvoering",
    underReview: "In beoordeling",
    completed: "Voltooid",
    selectLinkedCause: "Selecteer gekoppelde oorzaak",
  },
  
  // Actions page
  actionsPage: {
    title: "Acties",
    totalActions: "Totaal acties",
    pendingActions: "In behandeling",
    completedActions: "Voltooid",
    overdueActions: "Achterstallig",
    searchPlaceholder: "Zoek acties...",
    addAction: "Actie toevoegen",
    noActions: "Nog geen acties",
    noActionsDesc: "Acties verschijnen hier wanneer u aanbevelingen promoot van dreigingen of onderzoeken",
    source: "Bron",
    assignedTo: "Toegewezen aan",
    notStarted: "Niet gestart",
    completed: "Voltooid",
    filterByStatus: "Filter op status",
    allStatus: "Alle statussen",
    noSourceLinked: "Geen bron gekoppeld",
    linkedToInvestigation: "Gekoppeld aan onderzoek",
    linkedToThreat: "Gekoppeld aan dreiging",
    allDisciplines: "Alle disciplines",
  },
  
  // Library page
  library: {
    title: "Bibliotheek",
    failureModes: "Faalmodi",
    equipmentTypes: "Apparatuurtypen",
    maintenance: "Onderhoud",
    totalModes: "Totaal modi",
    categories: "Categorieën",
    searchPlaceholder: "Zoek faalmodi...",
    addFailureMode: "Faalmodus toevoegen",
    addEquipmentType: "Type toevoegen",
    editEquipmentType: "Apparatuurtype bewerken",
    noFailureModes: "Geen faalmodi gevonden",
    noMatches: "Geen overeenkomsten gevonden",
    tryAdjusting: "Probeer uw zoekopdracht of filters aan te passen",
    linkedEquipmentTypes: "Gekoppelde apparatuurtypen",
    selectEquipmentTypes: "Selecteer apparatuurtypen...",
    discipline: "Discipline",
    mechanical: "Mechanisch",
    electrical: "Elektrisch",
    instrumentation: "Instrumentatie",
    process: "Proces",
    icon: "Icoon",
    isoClass: "ISO klasse",
    typeId: "Type ID (uniek)",
    typesDefined: "typen gedefinieerd",
    severity: "Ernst",
    occurrence: "Frequentie",
    detectability: "Detecteerbaarheid",
    keywords: "Trefwoorden",
    addKeyword: "Voeg trefwoord toe en druk op Enter",
    recommendedActions: "Aanbevolen acties",
    addAction: "Voeg actie toe en druk op Enter",
    allCategories: "Alle categorieën",
    linked: "gekoppeld",
    selected: "Geselecteerd",
    types: "type(s)",
    editFailureMode: "Faalmodus bewerken",
    addFailureModeDesc: "Maak een nieuwe faalmodus aan.",
    updateFailureModeDesc: "Werk de faalmodus details hieronder bij.",
    category: "Categorie",
    equipment: "Apparatuur",
    equipmentPlaceholder: "bijv., Centrifugaalpomp",
    failureModeName: "Faalmodus naam",
    clickToSelect: "Klik om te selecteren/deselecteren (meerdere mogelijk)",
    selectFailureMode: "Selecteer een Faalmodus",
    selectFailureModeDesc: "Klik op een faalmodus in de lijst om de details te bekijken",
    riskScore: "Likelihood Score",
    linkedEquipmentTypes: "Gekoppelde apparatuurtypen",
    noLinkedTypes: "Geen apparatuurtypen gekoppeld",
    noRecommendedActions: "Geen aanbevolen acties gedefinieerd",
    // Validation translations
    validationStatus: "Validatiestatus",
    validated: "Gevalideerd",
    notValidated: "Nog Niet Gevalideerd",
    notValidatedDesc: "Deze faalmodus vereist menselijke validatie",
    validate: "Valideren",
    validateFailureMode: "Faalmodus Valideren",
    validateFailureModeDesc: "Bevestig dat deze faalmodus is beoordeeld en goedgekeurd door een vakexpert",
    validatingAs: "Valideert als deze gebruiker",
    validatorName: "Naam Validator",
    validatorNamePlaceholder: "bijv., Jan Jansen",
    validatorPosition: "Positie / Rol",
    validatorPositionPlaceholder: "bijv., Betrouwbaarheidsingenieur",
    confirmValidation: "Validatie Bevestigen",
    validationAdded: "Validatie succesvol toegevoegd",
    validationRemoved: "Validatie verwijderd",
    mechanism: "ISO 14224 Mechanisme",
    iso14224Mechanism: "ISO 14224 Mechanisme",
    pendingValidation: "In Afwachting van Validatie",
    noKeywords: "Geen trefwoorden",
    selectCategory: "Selecteer categorie",
    // New failure mode fields
    process: "Proces",
    processPlaceholder: "bijv., Extrusie, Compounding",
    potentialEffects: "Potentiële Effecten",
    potentialEffectsPlaceholder: "bijv., Productieverlies, veiligheidsrisico",
    potentialCauses: "Potentiële Oorzaken",
    potentialCausesPlaceholder: "bijv., Slijtage, vervuiling, verkeerde instellingen",
    duplicateNameError: "Er bestaat al een faalmodus met deze naam",
    exportExcel: "Exporteer Excel",
    exportSuccess: "Faalmodi succesvol geëxporteerd",
    exportError: "Exporteren van faalmodi mislukt",
  },
  
  // Equipment Manager
  equipment: {
    title: "Apparatuurbeheer",
    hierarchy: "Hiërarchie",
    tree: "Boom",
    levels: "Niveaus",
    properties: "Eigenschappen",
    addInstallation: "Installatie toevoegen",
    addChild: "Kind toevoegen",
    importList: "Lijst importeren",
    searchPlaceholder: "Zoek naam, beschrijving, tag...",
    matches: "resultaten",
    noEquipment: "Geen apparatuur in hiërarchie",
    addFirstEquipment: "Voeg uw eerste installatie toe om te beginnen",
    selectNode: "Selecteer een item",
    selectNodeDesc: "Klik op een apparatuuritem om de eigenschappen te bekijken en bewerken",
    installation: "Installatie",
    plant: "Fabriek/Eenheid",
    section: "Sectie",
    equipmentUnit: "Apparatuureenheid",
    subunit: "Subeenheid",
    maintainableItem: "Onderhoudbaar item",
    tag: "Tag",
    criticality: "Kriticiteit",
    selectCriticality: "Selecteer kriticiteit...",
    safetyCritical: "Veiligheidskritiek",
    productionCritical: "Productiekritiek",
    noCriticality: "Geen kriticiteit toegewezen",
    clearCriticality: "Kriticiteit wissen",
    safetyImpact: "Veiligheid",
    productionImpact: "Productie",
    environmentalImpact: "Milieu",
    reputationImpact: "Reputatie",
    overallCriticality: "Totale Kriticiteit",
    dragDropHint: "Sleep items om te herschikken of hiërarchie te wijzigen",
    unassigned: "Niet-toegewezen items",
    noSelection: "Geen selectie",
    selectFromHierarchy: "Selecteer een item uit de hiërarchie om eigenschappen te bekijken",
    dragDropTips: "Sleep & Laat Tips",
    dragTip1: "Sleep items om binnen gelijken te herschikken",
    dragTip2: "Laat vallen op boven/onderrand om te herschikken",
    dragTip3: "Laat vallen in midden om kind te maken",
    dragToReorder: "Sleep om te herschikken of te verplaatsen",
    section: "Sectie/Systeem",
    dragToHierarchy: "Sleep naar hiërarchie",
    importEquipmentList: "Apparatuurlijst importeren",
    pasteEquipmentList: "Apparatuurlijst plakken",
    orUpload: "of",
    uploadFile: "Bestand uploaden",
    supportedFormats: "Ondersteund: .txt, .csv, .xlsx, .xls, .pdf",
    parseList: "Lijst verwerken",
    riskScore: "Risicoscore",
    equipmentType: "Apparatuurtype",
    discipline: "Discipline",
    autoAssigned: "Automatisch toegewezen van apparatuurtype",
    selectLevel: "Selecteer niveau",
    assignToHierarchy: "Toewijzen aan hiërarchie",
    assignUnder: "Toewijzen onder",
    demoteTo: "Degraderen naar",
    selectNewParent: "Selecteer een nieuwe ouder",
    noValidParents: "Geen geldige ouder items gevonden",
    createFirst: "eerst",
    moving: "Verplaatsen",
    clickTarget: "Klik op een groen gemarkeerd doel",
    processStep: "Processtap",
    processStepPlaceholder: "bijv., Extrusie, Compounding, Mengen",
    processStepHint: "Wordt overgenomen door onderliggende items",
    selectEquipment: "Selecteer een apparatuuritem",
    exportExcel: "Exporteer Excel",
    exportSuccess: "Hiërarchie succesvol geëxporteerd",
    exportError: "Exporteren van hiërarchie mislukt",
  },

  // Hierarchy context menu
  hierarchy: {
    addThreat: "Observatie toevoegen",
    rightClickHint: "Rechtsklik voor opties",
    showDetails: "Details tonen",
    equipmentType: "Apparatuurtype",
    discipline: "Discipline",
    criticality: "Kriticiteit",
    notAssigned: "Niet toegewezen",
    editInManager: "Bewerken in Apparatuurbeheer",
  },
  
  // Chat
  chat: {
    title: "Dreiging melden",
    subtitle: "Beschrijf het probleem",
    placeholder: "Beschrijf het probleem...",
    welcomeMessage: "Hallo! Ik ben hier om u te helpen apparatuurdreigingen te melden. Beschrijf wat er gebeurt - noem de apparatuur en het probleem, en ik maak een dreigingsrecord voor u aan.",
    threatRecorded: "Dreiging succesvol vastgelegd.",
    attachPhoto: "Foto bijvoegen",
    voiceInput: "Spraakinvoer",
    startCapturing: "Begin met vastleggen van dreigingen",
    startCapturingDesc: "Beschrijf elk probleem of storing aan apparatuur. Ik analyseer het en help u prioriteiten te stellen.",
    trySaying: "Probeer te zeggen:",
    provideMoreDetails: "Geef meer details",
    voiceTranscribed: "Spraak getranscribeerd!",
    describeIssue: "Beschrijf de storing of het probleem...",
    newFailureMode: "Nieuwe storingsmodus",
    specifyFailureMode: "Geef de naam van de storingsmodus op:",
    enterFailureModeName: "Voer naam storingsmodus in...",
  },
  
  // Info dialog
  info: {
    title: "AssetIQ - Risicomethodologie",
    fmeaScoring: "Waarschijnlijkheidsscore",
    fmeaDescription: "Waarschijnlijkheidsscore wordt berekend met behulp van Failure Mode and Effects Analysis methodologie:",
    formula: "Waarschijnlijkheidsscore = (Ernst × Frequentie × Detectie) / 10",
    maxScore: "Maximale score: 100",
    severity: "Ernst (Reparatie Complexiteit)",
    severityScale: "1-3: Snel te repareren | 4-6: Normale reparatie | 7-9: Complexe reparatie | 10: Volledige vervanging",
    severity1to3: "1-3: Snel te repareren",
    severity4to6: "4-6: Normale reparatie",
    severity7to9: "7-9: Complexe reparatie",
    severity10: "10: Volledige vervanging",
    occurrence: "Frequentie (Verwacht Interval)",
    occurrenceScale: "1-3: 10-20 jaar | 4-6: 1-10 jaar | 7-9: 1-6 maanden | 10: Weken",
    occurrence1to3: "1-3: Elke 10-20 jaar",
    occurrence4to6: "4-6: Elke 1-10 jaar",
    occurrence7to9: "7-9: Elke 1-6 maanden",
    occurrence10: "10: Elke paar weken",
    detection: "Detectie (Moeilijkheid)",
    detectionScale: "1-3: Makkelijk te detecteren | 4-6: Gemiddeld | 7-9: Moeilijk | 10: Niet detecteerbaar",
    detection1to3: "1-3: Makkelijk te detecteren",
    detection4to6: "4-6: Gemiddeld",
    detection7to9: "7-9: Moeilijk",
    detection10: "10: Niet detecteerbaar",
    riskLevels: "Risiconiveaus",
    criticalityDimensions: "4-Dimensie Kriticiteitsbeoordeling",
    criticalityDimensionsDesc: "Kriticiteits Score wordt berekend uit 4 gewogen dimensies, elk beoordeeld 1-5:",
    safetyDimension: "Veiligheidsimpact",
    productionDimension: "Productie-impact",
    environmentalDimension: "Milieu-impact",
    reputationDimension: "Reputatie-impact",
    weight: "Gewicht",
    criticalityFormula: "Kriticiteits Score = (Veiligheid×25 + Productie×20 + Milieu×15 + Reputatie×10) / 3.5",
    overallCriticalityDesc: "Maximale Kriticiteits Score: 100",
    finalRiskFormula: "Uiteindelijke Risicoscore",
    finalRiskFormulaDesc: "De uiteindelijke risicoscore gebruikt gewogen componenten:",
    finalRiskFormulaCalc: "Risicoscore = (Kriticiteit × 0.75) + (Waarschijnlijkheid × 0.25)",
    quickTips: "Snelle tips",
    tip1: "Gebruik de + knop om nieuwe dreigingen te melden via chat",
    tip2: "Sleep apparatuur in de hiërarchie om te reorganiseren",
    tip3: "Klik op een dreiging om details te bekijken en onderzoeken te starten",
    tip4: "Gebruik de Oorzaakanalyse voor grondoorzaakanalyse",
    tip5: "Promoot aanbevelingen naar Acties voor tracking",
  },
  
  // Auth
  auth: {
    login: "Inloggen",
    register: "Registreren",
    email: "E-mail",
    password: "Wachtwoord",
    confirmPassword: "Bevestig wachtwoord",
    name: "Naam",
    loginTitle: "Welkom terug",
    loginSubtitle: "Log in op uw account",
    registerTitle: "Account aanmaken",
    registerSubtitle: "Begin met het beheren van apparatuurdreigingen",
    noAccount: "Heeft u geen account?",
    hasAccount: "Heeft u al een account?",
    signUp: "Registreren",
    signIn: "Inloggen",
    forgotPassword: "Wachtwoord vergeten?",
    forgotPasswordSubtitle: "Voer uw e-mail in en we sturen u een link om uw wachtwoord te resetten.",
    resetPassword: "Wachtwoord Resetten",
    newPassword: "Nieuw Wachtwoord",
    confirmPassword: "Bevestig Wachtwoord",
    resetLinkSent: "Reset link verzonden! Controleer uw e-mail.",
    passwordResetSuccess: "Wachtwoord is succesvol gereset.",
  },

  // AI Features
  ai: {
    riskAnalysis: "AI Risicoanalyse",
    causalIntelligence: "Causale Intelligentie",
    analyzeWithAi: "Analyseer met AI",
    analyzing: "Analyseren...",
    whyIsThisHappening: "Waarom gebeurt dit?",
    analyzingCauses: "Oorzaken analyseren...",
    riskScore: "Risicoscore",
    failureProbability: "Faalkans",
    timeToFailure: "Tijd tot falen",
    trendChange: "Trendwijziging",
    keyRiskFactors: "Belangrijkste risicofactoren",
    riskForecast: "Risicovoorspelling",
    keyInsights: "Belangrijkste inzichten",
    aiRecommendations: "AI Aanbevelingen",
    lastAnalyzed: "Laatst geanalyseerd",
    probableCauses: "Waarschijnlijke oorzaken",
    rankedByLikelihood: "gerangschikt op waarschijnlijkheid",
    supportingEvidence: "Ondersteunend bewijs",
    recommendedMitigations: "Aanbevolen maatregelen",
    contributingFactors: "Bijdragende factoren",
    analysisConfidence: "Analyse betrouwbaarheid",
    startInvestigationWithAi: "Start onderzoek met AI inzichten",
    creatingInvestigation: "Onderzoek aanmaken...",
    addAsAction: "Toevoegen als actie",
    addedAsAction: "Toegevoegd als actie",
    actionCreated: "Actie aangemaakt vanuit AI aanbeveling!",
    addToThreat: "Toevoegen aan dreigingsaanbevelingen",
    alreadyAdded: "Reeds toegevoegd",
    recommendationAdded: "Aanbeveling toegevoegd aan dreiging!",
    recommendationExists: "Aanbeveling bestaat al",
    recommendationFailed: "Aanbeveling toevoegen mislukt",
    investigationCreated: "Onderzoek aangemaakt met AI inzichten!",
    increasing: "Stijgend",
    stable: "Stabiel",
    decreasing: "Dalend",
    highConfidence: "Hoge betrouwbaarheid",
    mediumConfidence: "Gemiddelde betrouwbaarheid",
    lowConfidence: "Lage betrouwbaarheid",
    veryLikely: "Zeer waarschijnlijk",
    likely: "Waarschijnlijk",
    possible: "Mogelijk",
    unlikely: "Onwaarschijnlijk",
    technicalCause: "Technisch",
    humanFactor: "Menselijke factor",
    maintenanceIssue: "Onderhoud",
    designIssue: "Ontwerpprobleem",
    organizationalFactor: "Organisatorisch",
    externalCondition: "Extern",
    causesIdentified: "waarschijnlijke oorzaken geïdentificeerd",
    unknown: "Onbekend",
    missingLibraryData: "Ontbrekende bibliotheekgegevens",
    missingLibraryDataDesc: "De volgende items ontbreken in uw bibliotheek. Voeg ze toe voor betere AI-analyse nauwkeurigheid:",
    goToLibrary: "Ga naar bibliotheek",
  },

  // Threat Detail
  threatDetail: {
    title: "Dreigingsdetails",
    backToThreats: "Terug naar dreigingen",
    riskScoreCard: "Risicoscore",
    threatInfo: "Dreigingsinformatie",
    equipmentInfo: "Apparatuurinformatie",
    causeAnalysis: "Oorzaakanalyse",
    recommendedActions: "Aanbevolen acties",
    addAction: "Actie toevoegen",
    createAction: "Actie aanmaken",
    actionTitle: "Titel",
    actionDescription: "Beschrijving",
    actionPriority: "Prioriteit",
    actionAssignee: "Toegewezen aan",
    actionDueDate: "Vervaldatum",
    deleteConfirm: "Weet u het zeker?",
    deleteWarning: "Dit verwijdert deze dreiging en alle bijbehorende gegevens permanent.",
    mitigated: "Gemitigeerd",
    createdAt: "Aangemaakt",
  },

  // Maintenance Strategies
  maintenance: {
    title: "Onderhoudsstrategieën",
    subtitle: "AI-gegenereerde onderhoudsplannen per apparatuurtype",
    generateStrategy: "Strategie genereren",
    generateAll: "Alles genereren",
    generating: "Genereren...",
    noStrategies: "Nog geen onderhoudsstrategieën",
    noStrategiesDesc: "Genereer onderhoudsstrategieën voor uw apparatuurtypen",
    selectEquipmentType: "Selecteer apparatuurtype",
    operatorRounds: "Operatorronden",
    detectionSystems: "Detectiesystemen",
    scheduledMaintenance: "Gepland onderhoud",
    correctiveActions: "Corrigerende acties",
    emergencyProcedures: "Noodprocedures",
    spareParts: "Reserveonderdelen",
    safetyCritical: "Veiligheidskritiek",
    productionCritical: "Productiekritiek",
    frequency: "Frequentie",
    discipline: "Discipline",
    resources: "Middelen",
    duration: "Duur",
    detects: "Detecteert",
    prevents: "Voorkomt",
    addresses: "Adresseert",
    checksFor: "Controleert op",
    sensor: "sensor",
    sensors: "sensoren",
    task: "uitvoering",
    tasks: "uitvoeringen",
    action: "actie",
    round: "ronde",
    rounds: "rondes",
    procedure: "procedure",
    procedures: "procedures",
    part: "onderdeel",
    parts: "onderdelen",
    deleteStrategy: "Strategie verwijderen?",
    deleteStrategyDesc: "Dit verwijdert permanent de onderhoudsstrategie voor",
    allCriticalityLevels: "alle kriticiteitsniveaus",
    autoGenerated: "Automatisch gegenereerd vanuit FMEA",
    criticalityLevels: "kriticiteitsniveaus",
    editItem: "Item bewerken",
    addItem: "Item toevoegen",
    itemName: "Itemnaam",
    checklistItems: "Checklistitems",
    failureModesAddressed: "Aangepakte faalmodi",
    failureModesDetected: "Gedetecteerde faalmodi",
    sensorType: "Sensortype",
    alertThreshold: "Waarschuwingsdrempel",
    alarmThreshold: "Alarmdrempel",
    tripThreshold: "Uitschakeldrempel",
    partNumber: "Onderdeelnummer",
    quantity: "Hoeveelheid",
    minStock: "Min. voorraad",
    leadTime: "Levertijd",
    estimatedCost: "Geschatte kosten",
    triggerConditions: "Triggercondities",
    immediateActions: "Onmiddellijke acties",
    notificationList: "Notificatielijst",
  },

  // Reliability Performance
  reliability: {
    title: "Betrouwbaarheidsprestaties",
    subtitle: "Holistisch overzicht van betrouwbaarheidsbeheer over uw assethiërarchie",
    overallScore: "Totaalscore",
    equipmentHealth: "Apparatuurgezondhied",
    dimensionBreakdown: "Dimensie-uitsplitsing",
    criticalityDimension: "Kriticiteit",
    incidentsDimension: "Incidenten",
    investigationsDimension: "Onderzoeken",
    maintenanceDimension: "Onderhoud",
    reactionsDimension: "Reacties",
    threatsDimension: "Dreigingen",
    withCriticality: "Met kriticiteit",
    openObservations: "Open dreigingen",
    totalInvestigations: "Onderzoeken",
    totalActions: "Totaal acties",
    filterByLevel: "Filter op niveau",
    allLevels: "Alle niveaus",
    searchEquipment: "Zoek apparatuur...",
    noEquipment: "Geen apparatuur gevonden",
    addEquipmentToSee: "Voeg apparatuur toe aan uw hiërarchie om betrouwbaarheidsscores te zien",
    frameworkInfo: "Framework methodologie",
    frameworkDescription: "De betrouwbaarheidsprestatie score wordt berekend over 6 dimensies:",
    criticalityDesc: "Apparatuurhiërarchie volledigheid en kriticiteitstoewijzingen",
    incidentsDesc: "Incidentenregistraties en positieve validatie",
    investigationsDesc: "Cross-asset analyse dekking",
    maintenanceDesc: "Actieve onderhoudsplannen en reserveonderdelen",
    reactionsDesc: "Duidelijke reactieplannen (middelen, ondersteuning, stilstand)",
    threatsDesc: "Niet-gemitigeerd dreigingsbeheer",
    good: "Goed",
    fair: "Redelijk",
    poor: "Slecht",
    crit: "Krit",
    maint: "Onderh",
  },

  // Task Scheduler
  taskScheduler: {
    title: "Taakplanner",
    subtitle: "Beheer taaksjablonen, plannen en schema's",
    generateExecutions: "Genereer schema",
    newTemplate: "Taak ontwerpen",
    totalExecutions: "Totaal uitvoeringen",
    planned: "Gepland",
    overdue: "Achterstallig",
    executions: "Schema",
    plans: "Plannen",
    templates: "Taakontwerpen",
    allStatus: "Alle statussen",
    searchTemplates: "Zoek taakontwerpen...",
    allDisciplines: "Alle disciplines",
    operations: "Operaties",
    maintenance: "Onderhoud",
    laboratory: "Laboratorium",
    inspection: "Inspectie",
    engineering: "Engineering",
    noExecutionsFound: "Geen uitvoeringen gevonden",
    generateFromPlans: "Genereer vanuit plannen",
    execution: "Taakplanner",
    equipment: "Apparatuur",
    scheduled: "Gepland",
    start: "Start",
    complete: "Voltooien",
    newPlan: "Nieuw plan",
    noPlansYet: "Nog geen uitvoeringsplannen aangemaakt",
    createPlansDesc: "Maak plannen vanuit sjablonen om terugkerende uitvoeringen te plannen",
    createFirstPlan: "Eerste plan aanmaken",
    active: "Actief",
    inactive: "Inactief",
    deletePlan: "Plan verwijderen",
    every: "Elke",
    next: "Volgende",
    linkedForm: "Gekoppeld formulier",
    selectForm: "Selecteer een formulier",
    noTemplatesFound: "Geen taakontwerpen gevonden",
    createFirstTemplate: "Maak uw eerste sjabloon aan",
    noDescription: "Geen beschrijving",
    usedInPlans: "Gebruikt in",
    editTemplate: "Uitvoeringssjabloon bewerken",
    createTemplate: "Uitvoeringssjabloon aanmaken",
    strategy: "Strategie",
    preventive: "Preventief",
    predictive: "Voorspellend",
    detective: "Detectief",
    corrective: "Correctief",
    defaultInterval: "Standaard interval",
    days: "Dagen",
    weeks: "Weken",
    months: "Maanden",
    durationMin: "Duur (min)",
    saving: "Opslaan...",
    saveChanges: "Wijzigingen opslaan",
    completeExecution: "Uitvoering voltooien",
    completing: "Voltooien",
    completionNotes: "Voltooiingsnotities",
    anyObservations: "Eventuele observaties of notities...",
    needsFollowUp: "Vervolg actie nodig",
    markComplete: "Markeer als voltooid",
    deleteExecution: "Uitvoering verwijderen",
    deleteExecutionConfirm: "Weet u zeker dat u deze uitvoering wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt.",
    deleting: "Verwijderen...",
    createPlan: "Uitvoeringsplan aanmaken",
    createPlanDesc: "Plan terugkerende uitvoeringen voor apparatuur",
    executionTemplate: "Taakontwerp",
    selectTemplate: "Selecteer een taakontwerp",
    selectEquipment: "Selecteer apparatuur",
    interval: "Interval",
    inheritedFromTemplate: "Overgenomen van sjabloon",
    reset: "Reset",
    templateDefault: "Taakontwerp standaard",
    beginDate: "Begindatum",
    selectDate: "Selecteer datum",
    today: "Vandaag",
    clear: "Wissen",
    whenToStart: "Wanneer te beginnen met plannen",
    endDateOptional: "Einddatum (optioneel)",
    whenToStop: "Wanneer te stoppen met plannen",
    linkedFormOptional: "Gekoppeld formulier (optioneel)",
    selectFormTemplate: "Selecteer een formuliersjabloon",
    noForm: "Geen formulier",
    linkFormDesc: "Koppel een formulier om in te vullen tijdens uitvoering",
    optionalNotes: "Optionele notities over dit plan",
    // Ad-hoc execution
    executeNow: "Nu uitvoeren",
    executeAdhocTitle: "Ad-hoc uitvoering aanmaken",
    executeAdhocDesc: "Maak een eenmalige taakuitvoering van dit sjabloon zonder terugkerend schema",
    selectedTemplate: "Geselecteerd sjabloon",
    noEquipment: "Geen specifieke apparatuur",
    priority: "Prioriteit",
    notes: "Notities",
    adhocNotesPlaceholder: "Optionele notities over deze ad-hoc uitvoering...",
    createAdhocTask: "Uitvoering aanmaken",
    adhocTaskCreated: "Ad-hoc uitvoering succesvol aangemaakt",
    template: "Sjabloon",
    // Ad-hoc template creation
    adhocOnly: "Alleen ad-hoc",
    adhocOnlyDesc: "Geen terugkerend schema - voer handmatig uit wanneer nodig",
    adhocLabel: "Ad-hoc",
    adhocTemplateHint: "Ad-hoc taak",
    adhocPlanDesc: "Dit is een ad-hoc sjabloon - geen terugkerend schema nodig",
    intervalOptional: "Interval (Optioneel voor ad-hoc)",
    editPlan: "Uitvoeringsplan bewerken",
    editPlanDesc: "Wijzig planinstellingen en planning",
    planStatus: "Planstatus",
    planStatusDesc: "Schakel dit plan in of uit",
  },

  // Forms
  forms: {
    title: "Formulierontwerper",
    subtitle: "Maak en beheer gegevensverzamelingsformulieren",
    templates: "Sjablonen",
    submissions: "Inzendingen",
    warnings: "Waarschuwingen",
    critical: "Kritiek",
    operations: "Operaties",
    maintenance: "Onderhoud",
    inspection: "Inspectie",
    lab: "Lab",
    noTemplatesYet: "Nog geen formuliersjablonen",
    noTemplatesDesc: "Maak uw eerste formuliersjabloon om gegevens te verzamelen",
    noSubmissionsYet: "Nog geen inzendingen",
    noSubmissionsDesc: "Inzendingen verschijnen hier wanneer formulieren worden ingevuld",
    templateName: "Naam",
    templateDescription: "Beschrijving",
    discipline: "Discipline",
    requireSignature: "Handtekening vereist",
    allowPartialSubmit: "Gedeeltelijk indienen toestaan",
    formFields: "Formuliervelden",
    noFieldsYet: "Nog geen velden toegevoegd",
    addFieldHint: "Klik op \"Veld toevoegen\" om uw formulier op te bouwen",
    label: "Label",
    fieldType: "Veldtype",
    notes: "Notities",
    // Documents
    documents: "Documenten",
    referenceDocuments: "Referentiedocumenten",
    referenceDocumentsHint: "Voeg handleidingen, SOP's of gidsen toe die met AI kunnen worden doorzocht tijdens uitvoering",
    addDocument: "Document toevoegen",
    pendingUpload: "Wachtend op upload",
    noDocuments: "Geen documenten bijgevoegd",
    noDocumentsHint: "Upload PDF's, handleidingen of referentiemateriaal",
    attachedDocuments: "Bijgevoegde documenten",
    noDocumentsAttached: "Geen documenten aan dit formulier gekoppeld",
    aiDocumentSearch: "AI Documentzoeken",
    searchDocumentsPlaceholder: "Stel een vraag over de bijgevoegde documenten...",
    askAI: "Vraag AI",
    documentUploaded: "Document succesvol geüpload",
  },

  // Decision Engine
  decisionEngine: {
    title: "Beslissingsmotor",
    subtitle: "Automatische leerregels & suggesties",
    pending: "In afwachting",
    approved: "Goedgekeurd",
    executed: "Uitgevoerd",
    highPriority: "Hoge prioriteit",
    rulesActive: "Regels actief",
    allStatus: "Alle statussen",
    allPriority: "Alle prioriteiten",
    noSuggestionsYet: "Nog geen suggesties",
    noSuggestionsDesc: "Klik op \"Regels evalueren\" om suggesties te genereren op basis van uw gegevens",
    noRulesConfigured: "Geen regels geconfigureerd",
    noRulesDesc: "Regels verschijnen hier zodra ze zijn geïnitialiseerd",
    enabled: "Ingeschakeld",
    enabledDesc: "Regel genereert suggesties wanneer ingeschakeld",
    autoExecute: "Automatisch uitvoeren",
    autoExecuteDesc: "Suggesties automatisch uitvoeren zonder goedkeuring",
    configuration: "Configuratie",
    notesOptional: "Notities (optioneel)",
    reasonOptional: "Reden (optioneel)",
    recommendedAction: "Aanbevolen actie",
    autoExecuteNote: "Deze regel wordt automatisch uitgevoerd",
    rejectionReason: "Afwijzingsreden",
    rejected: "Afgewezen",
  },

  // Analytics Dashboard
  analyticsDashboard: {
    title: "Analyse Dashboard",
    subtitle: "Realtime betrouwbaarheidsinformatie",
    last7Days: "Laatste 7 dagen",
    last30Days: "Laatste 30 dagen",
    last90Days: "Laatste 90 dagen",
    topRisksByRPN: "Top risico's op RPN",
    topRisksDesc: "Apparatuur faalmodi met het hoogste risico",
    noRiskData: "Geen risicogegevens beschikbaar",
    failureModePareto: "Faalmodus Pareto",
    failureModeParetoDesc: "Meest waargenomen faalmodi",
    noObservationData: "Geen observatiegegevens",
    equipmentRiskRanking: "Apparatuur risicorangschikking",
    equipmentRiskDesc: "Apparatuur op basis van geaggregeerd faalmodusrisico",
    noEquipmentData: "Geen apparatuurgegevens",
    detectionEffectiveness: "Detectie-effectiviteit",
    detectionEffectivenessDesc: "Taaksjablonen op basis van probleemdetectie",
    noDataYet: "Nog geen gegevens",
    noConcerns: "Geen zorgen",
    taskWorkload: "Taakbelasting",
    taskWorkloadDesc: "Komende 7-daagse taakverdeling",
    noScheduledTasks: "Geen geplande taken",
  },

  // User Management
  userManagement: {
    title: "Gebruikersbeheer",
    subtitle: "Beheer gebruikersrollen en rechten",
    allRoles: "Alle rollen",
    noUsersFound: "Geen gebruikers gevonden",
    user: "Gebruiker",
    role: "Rol",
    department: "Afdeling",
    lastLogin: "Laatste login",
    editUserProfile: "Gebruikersprofiel bewerken",
    phone: "Telefoon",
    position: "Positie",
    changeUserRole: "Gebruikersrol wijzigen",
    score: "SCORE",
    // Foto upload
    uploadPhoto: "Foto Uploaden",
    changePhoto: "Foto Wijzigen",
    removePhoto: "Foto Verwijderen",
    photoUploading: "Uploaden...",
    photoUploaded: "Foto succesvol geüpload",
    photoRemoved: "Foto verwijderd",
    photoError: "Foto uploaden mislukt",
    invalidFileType: "Ongeldig bestandstype. Gebruik JPEG, PNG, GIF of WebP.",
    fileTooLarge: "Bestand te groot. Maximale grootte is 5MB.",
    // Afbeelding Editor
    editPhoto: "Foto Bewerken",
    zoom: "Zoom",
    brightness: "Helderheid",
    contrast: "Contrast",
    rotateLeft: "Naar Links Draaien",
    rotateRight: "Naar Rechts Draaien",
    flipHorizontal: "Horizontaal Spiegelen",
    flipVertical: "Verticaal Spiegelen",
    reset: "Resetten",
    savePhoto: "Foto Opslaan",
    saving: "Opslaan...",
  },

  // User Statistics
  userStatistics: {
    title: "Gebruikersstatistieken",
    subtitle: "Systeemgebruik en betrokkenheidsoverzicht",
    activeUsers: "Actieve gebruikers",
    totalSessions: "Totaal sessies",
    totalViews: "Totaal weergaven",
    avgSessionDuration: "Gem. duur",
    mostUsedModule: "Meest gebruikt",
    leastUsedModule: "Minst gebruikt",
    moduleUsage: "Module gebruik",
    usageDistribution: "Gebruiksverdeling",
    dailyActiveUsers: "Dagelijks actieve gebruikers",
    dailyViews: "Dagelijkse weergaven",
    userActivity: "Gebruikersactiviteit",
    featureUsage: "Functie gebruik",
    overview: "Overzicht",
    modules: "Modules",
    users: "Gebruikers",
    actions: "Acties",
    noDataAvailable: "Geen gegevens beschikbaar",
    accessRestricted: "Toegang beperkt",
    accessDeniedMessage: "U hebt geen toestemming om gebruikersstatistieken te bekijken.",
    allRoles: "Alle rollen",
    allActivity: "Alle activiteit",
    active: "Actief",
    lowActivity: "Lage activiteit",
    inactive: "Inactief",
    lastActive: "Laatst actief",
    sessions: "Sessies",
    mostUsed: "Meest gebruikt",
    totalCount: "Totaal aantal",
    uniqueUsers: "Unieke gebruikers",
    percentOfTotal: "% van totaal",
    avgTimeSpent: "Gem. tijd (s)",
    today: "Vandaag",
    last7Days: "Laatste 7 dagen",
    last30Days: "Laatste 30 dagen",
  },

  // Feedback
  feedback: {
    title: "Feedback",
    subtitle: "Uw inzendingen",
    noFeedbackYet: "Nog geen feedback",
    noFeedbackDesc: "Deel uw gedachten, meld problemen of doe suggesties voor verbeteringen.",
    sendFeedback: "Feedback versturen",
    newFeedback: "Feedback versturen",
    newFeedbackDesc: "Deel uw gedachten, meld een probleem of doe een suggestie voor verbetering.",
    type: "Type",
    typeIssue: "Probleem",
    typeImprovement: "Verbetering",
    typeGeneral: "Algemeen",
    severity: "Ernst",
    selectSeverity: "Selecteer ernst",
    message: "Bericht",
    messagePlaceholder: "Beschrijf uw feedback...",
    messageRequired: "Voer een bericht in",
    screenshot: "Schermafbeelding",
    attachScreenshot: "Schermafbeelding bijvoegen",
    submit: "Versturen",
    submitted: "Feedback succesvol verstuurd",
    updated: "Feedback succesvol bijgewerkt",
    deleted: "Feedback verwijderd",
    statusUpdated: "Status bijgewerkt",
    deleteConfirm: "Feedback verwijderen?",
    deleteConfirmDesc: "Deze actie kan niet ongedaan worden gemaakt. Dit verwijdert uw feedback permanent.",
    submittedBy: "Ingediend door",
    response: "Reactie",
    editFeedback: "Feedback bewerken",
    editFeedbackDesc: "Werk uw feedback details bij.",
    statusNew: "Nieuw",
    statusInReview: "In behandeling",
    statusResolved: "Opgelost",
    statusPlanned: "Gepland",
    statusWontFix: "Wordt niet opgelost",
  },
};

const translations = { en, nl };

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("reliabilityos_language");
    return saved || "en";
  });

  useEffect(() => {
    localStorage.setItem("reliabilityos_language", language);
  }, [language]);

  const t = (key) => {
    const keys = key.split(".");
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === "en" ? "nl" : "en");
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
